force-app/main/default/objects/Trigger_switch__c/Trigger_switch__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom setting to allow turn off triggers:
When given trigger is &quot;checked&quot; then trigger is deactivated.</description>
    <label>Trigger switch</label>
</CustomObject>

force-app/main/default/objects/Trigger_switch__c/fields/EmailMessage__c.field-meta.xml
<CustomField>
    <fullName>EmailMessage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EmailMessage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TriggerSwitchServiceTest.cls
/*****************************************************************************************************************************
Name: TriggerSwitchService

Purpose: Unit test for  TriggerSwitchService

History
-------
VERSION AUTHOR                          DATE            DETAIL  FEATURES/CSR/TTP
1.0 -   pczechumski@salesforce.com      19/04/2016      INITIAL DEVELOPMENT
*******************************************************************************************************************************/
@isTest (seeAllData=false)
private  with sharing class TriggerSwitchServiceTest {
	@isTest
	static void shouldReturnFalseForNotExisting(){
		System.assert(!TriggerSwitchService.isTriggerSwitchOff('NoExistingTigger'), 
			'Should return false for not existing trigger');
	}

	@isTest
	static void shouldReturnValueFromCS(){
		Trigger_switch__c ts =  new Trigger_switch__c(EmailMessage__c = false);
		insert ts;
		System.assert(!TriggerSwitchService.isTriggerSwitchOff('EmailMessage'), 
			'Should return false for active trigger');
		ts.EmailMessage__c = true;
		update ts;

		System.assert(TriggerSwitchService.isTriggerSwitchOff('EmailMessage'), 
			'Should return true for swith off trigger ');
	}
}