force-app/main/default/objects/Case_Supplier__c/Case_Supplier__c.object-meta.xml
<CustomObject>
    <label>Case Supplier</label>
    <nameField>
        <displayFormat>CS{0000000}</displayFormat>
        <label>Ref#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Suppliers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Supplier__c/fields/Procurement__c.field-meta.xml
<CustomField>
    <fullName>Procurement__c</fullName>
    <label>Procurement</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Suppliers</relationshipLabel>
    <relationshipName>Case_Suppliers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Supplier__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Procurements Participated In</relationshipLabel>
    <relationshipName>Case_Suppliers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Master_Framework__c/Master_Framework__c.object-meta.xml
<CustomObject>
    <description>This object represents Framework related to Opportunity, Enquiry, and Category.</description>
    <label>Framework</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Frameworks</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Framework_Lot__c/Master_Framework_Lot__c.object-meta.xml
<CustomObject>
    <description>Object to hold information regarding Framework Lots</description>
    <label>Framework Lot</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Framework Lots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Framework_Lot__c/fields/Master_Framework__c.field-meta.xml
<CustomField>
    <fullName>Master_Framework__c</fullName>
    <description>Holds reference to Master Framework</description>
    <label>Framework</label>
    <referenceTo>Master_Framework__c</referenceTo>
    <relationshipLabel>Framework Lots</relationshipLabel>
    <relationshipName>Framework_Lots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Master_Framework_Lot__c/fields/Master_Framework_Lot_Number__c.field-meta.xml
<CustomField>
    <fullName>Master_Framework_Lot_Number__c</fullName>
    <description>Lot number field in SAFIRE</description>
    <inlineHelpText>Official number of the FW Lot.  Appears on the website</inlineHelpText>
    <label>Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ops_Workflow_Templates__c/Ops_Workflow_Templates__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting holding procurement templates and their mapping to stages and stage duration</description>
    <label>Ops Workflow Templates</label>
</CustomObject>

force-app/main/default/objects/Ops_Workflow_Templates__c/fields/Record_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Name__c</fullName>
    <description>Keeps record type developer name for which this template applies to.</description>
    <label>Record Type Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Supplier_Framework_Lot__c/Supplier_Framework_Lot__c.object-meta.xml
<CustomObject>
    <label>Framework Lot Supplier</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Framework Lot Suppliers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Framework_Lot__c/fields/Framework__c.field-meta.xml
<CustomField>
    <fullName>Framework__c</fullName>
    <formula>HYPERLINK(Master_Framework_Lot__r.Master_Framework__r.Id, Master_Framework_Lot__r.Master_Framework__r.Name)</formula>
    <label>Framework</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Supplier_Framework_Lot__c/fields/Master_Framework_Lot__c.field-meta.xml
<CustomField>
    <fullName>Master_Framework_Lot__c</fullName>
    <label>Framework Lot</label>
    <referenceTo>Master_Framework_Lot__c</referenceTo>
    <relationshipLabel>Framework Lot Suppliers</relationshipLabel>
    <relationshipName>Supplier_Framework_Lots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Supplier_Framework_Lot__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Framework Lot Suppliers</relationshipLabel>
    <relationshipName>Supplier_Framework_Lots</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/CaseSupplierTriggerHelperTest.cls
/*********************************************************************
 Name:  CaseSupplierTriggerHelperTest
 Copyright © 2016  Salesforce
 ======================================================
 ======================================================
 Purpose: test class for CaseSupplierTriggerHelper                                                         
 -------                                                            
 ======================================================
 ======================================================
 History                                                            
 -------                                                            
 VERSION  AUTHOR            DATE             DETAIL				Description
   1.0   Klea Kolaric		2016-04-07		Initial version 	US601
   1.1 	 Cezary Zeleznicki	2016-11-04		Procurement RT change
 *********************************************************************/
@isTest
private class CaseSupplierTriggerHelperTest {
	
	static final String ORG_NAME = 'Test Organisation';
	static final String SUP_NAME = 'Test Supplier';
	
	@testSetup
	static void setupTest()
	{
		// create custom settings
		insert UnitTestDataFactory.createOpsWorkflowStages();
		List<Ops_Workflow_Templates__c> wftmps = UnitTestDataFactory.createOpsWorkflowTemplates();
		for(Ops_Workflow_Templates__c wftmp : wftmps) {
			wftmp.Record_Type_Name__c = CaseSupplierTriggerHelper.PL_CALLOFFDIRECTAWARD;
		}
		insert wftmps;
		
		Account org = UnitTestDataFactory.createOrganisationAccount(ORG_NAME);
		Account sup = UnitTestDataFactory.createSupplierAccount(SUP_NAME);
		insert new List<Account>{org,sup};
		
		Master_Framework__c mf = new Master_Framework__c(Name='Mater Framework');
		insert mf;
		Master_Framework_Lot__c mfl = new Master_Framework_Lot__c(Name='Lot 1234', Master_Framework_Lot_Number__c='1234', Master_Framework__c=mf.id);
		insert mfl;
		
		Case c = UnitTestDataFactory.createProcurementCase(org.id);
		c.RecordTypeId = RecordTypeFetcher.fetchCaseRtId(CaseSupplierTriggerHelper.PL_CALLOFFDIRECTAWARD);
		c.Framework__c = mf.Id;
		c.Framework_Lot__c = mfl.id;
		insert c;
		
		insert new Supplier_Framework_Lot__c(Master_Framework_Lot__c=mfl.id, Supplier__c=sup.id);
	}
	
	static testMethod void testValidationForCallOffDirectAward_HappyPath_supplierAddedToCase()
	{
		Case c = [select id from Case where Account.Name = :ORG_NAME limit 1];
		Account supp = [select id from Account where Name = :SUP_NAME limit 1];
		
		Test.startTest();
		insert new Case_Supplier__c(Procurement__c=c.Id, Supplier__c=supp.Id);
		Test.stopTest();
		system.assertEquals(1,[select count() from Case_Supplier__c where Procurement__c = :c.Id and Supplier__c = :supp.Id],
			'Case Supplier should be created.');
	}
	
	static testMethod void testValidationForCallOffDirectAward_noFrameworkLot_throwException()
	{
		Case c = [select id, Framework_Lot__c from Case where Account.Name = :ORG_NAME limit 1];
		c.Framework_Lot__c = null;
		update c;
		Account supp = [select id from Account where Name = :SUP_NAME limit 1];
		
		Test.startTest();
		Boolean hadError = false;
		try
		{
			insert new Case_Supplier__c(Procurement__c=c.Id, Supplier__c=supp.Id);
		}
		catch(exception e)
		{
			hadError = true;
		}
		Test.stopTest();
		system.assert(hadError,'Exception should have been thrown.');
	}
	
	static testMethod void testValidationForCallOffDirectAward_supplerNotOnFrameworkLot_throwException()
	{
		Case c = [select id, Framework_Lot__c from Case where Account.Name = :ORG_NAME limit 1];
		Account supp = [select id from Account where Name = :SUP_NAME limit 1];
		delete [select id from Supplier_Framework_Lot__c];	// remove framework lot-supplier association
		
		Test.startTest();
		Boolean hadError = false;
		try
		{
			insert new Case_Supplier__c(Procurement__c=c.Id, Supplier__c=supp.Id);
		}
		catch(exception e)
		{
			hadError = true;
		}
		Test.stopTest();
		system.assert(hadError,'Exception should have been thrown.');
	}
    
}