force-app/main/default/objects/Case_Supplier__c/Case_Supplier__c.object-meta.xml
<CustomObject>
    <label>Case Supplier</label>
    <nameField>
        <displayFormat>CS{0000000}</displayFormat>
        <label>Ref#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Suppliers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Supplier__c/fields/Procurement__c.field-meta.xml
<CustomField>
    <fullName>Procurement__c</fullName>
    <label>Procurement</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Suppliers</relationshipLabel>
    <relationshipName>Case_Suppliers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <description>This object holds the Pillars, CCS Categories, CCS Subcategories, CAS Master Categories, CAS Categories, CAS Sub Categories and CAS Codes. They are hierarchical, and this is achieved via the [CategoryType] field, and the [Parent] self-lookup.</description>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Reference__c/Contract_Reference__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Lookup table to hold next number for a given master category code and year</description>
    <label>Contract Reference</label>
</CustomObject>

force-app/main/default/objects/Contract_Reference__c/fields/Next_Number__c.field-meta.xml
<CustomField>
    <fullName>Next_Number__c</fullName>
    <label>Next Number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master_Framework__c/Master_Framework__c.object-meta.xml
<CustomObject>
    <description>This object represents Framework related to Opportunity, Enquiry, and Category.</description>
    <label>Framework</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Frameworks</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Framework_Lot__c/Master_Framework_Lot__c.object-meta.xml
<CustomObject>
    <description>Object to hold information regarding Framework Lots</description>
    <label>Framework Lot</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Framework Lots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Framework_Lot__c/fields/Master_Framework__c.field-meta.xml
<CustomField>
    <fullName>Master_Framework__c</fullName>
    <description>Holds reference to Master Framework</description>
    <label>Framework</label>
    <referenceTo>Master_Framework__c</referenceTo>
    <relationshipLabel>Framework Lots</relationshipLabel>
    <relationshipName>Framework_Lots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Supplier_Framework_Lot__c/Supplier_Framework_Lot__c.object-meta.xml
<CustomObject>
    <label>Framework Lot Supplier</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Framework Lot Suppliers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Framework_Lot__c/fields/Master_Framework_Lot__c.field-meta.xml
<CustomField>
    <fullName>Master_Framework_Lot__c</fullName>
    <label>Framework Lot</label>
    <referenceTo>Master_Framework_Lot__c</referenceTo>
    <relationshipLabel>Framework Lot Suppliers</relationshipLabel>
    <relationshipName>Supplier_Framework_Lots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/bg_ProcurementSuppliers_Test.cls
/*****************************************************************
 * bg_ProcurementSuppliers_Test
 *
 * Test Classs for bg_ProcurementSuppliers
 * 
 * Author: Josh Adams
 * Created: 06/11/2017
 * Changes: 
 *
******************************************************************/

@IsTest
public class bg_ProcurementSuppliers_Test {

    public static testMethod void testRecreateCaseSuppliers()
    {
        final Integer NUM_OF_FRAMEWORK_LOT_SUPPLIERS = 200; // Framework Lot Suppliers to create

        // Set up data
        insert new Contract_Reference__c(NAME = 'CS' + Date.today().year().format().right(2), Next_Number__c = 1);
        Account acc = bg_UnitTestHelper.createSupplierAccount('Test Supplier');
        insert acc;
        List<Category__c> cats = new List<Category__c>();
        Category__c cat = bg_UnitTestHelper.createCategory('Test Category','CAS Category','CS');
        Category__c subcat = bg_UnitTestHelper.createCategory('Test Sub Category','CCS Sub Category');
        cats.add(cat);
        cats.add(subcat);
        insert cats;
        System.debug(logginglevel.ERROR, '**JA**: Sub Cat ' + subcat);
        Master_Framework__c framework = bg_UnitTestHelper.createFramework('Test Framework', subcat.id);
        insert framework;
        Master_Framework_Lot__c frameworkLot = bg_UnitTestHelper.createFrameworkLot('Test Framwork Lot', framework.Id);
        insert frameworkLot;
        List<Supplier_Framework_Lot__c> frameworkLotSuppliers = new List<Supplier_Framework_Lot__c>();
        for (Integer i = 0; i < NUM_OF_FRAMEWORK_LOT_SUPPLIERS; i++) {
            Supplier_Framework_Lot__c newFLS = bg_UnitTestHelper.createFrameworkLotSupplier(frameworkLot.Id, acc.Id);
            frameworkLotSuppliers.add(newFLS);
        }
        insert frameworkLotSuppliers;

        // Insert case
        bg_ProcurementSuppliers.testContextSuppress = true; // This prevents the batch from running on both insert and test invokation, which casuses timing issues
        Case testCase = bg_UnitTestHelper.createProcurementCase('Test Case', acc.Id, cat.Id, framework.Id, frameworkLot.Id);
        insert testCase;
        bg_ProcurementSuppliers.testContextSuppress = false;

        // Execute recreateCaseSuppliers()
        Test.startTest();
            bg_ProcurementSuppliers.recreateCaseSuppliers(new List<Id>{testcase.Id});
        Test.stopTest();

        // Verify Case Suppliers have been generated
        List<Case_Supplier__c> csResult = [SELECT Id FROM Case_Supplier__c WHERE Procurement__c = :testcase.ID];
        System.assertEquals(NUM_OF_FRAMEWORK_LOT_SUPPLIERS, csResult.size(), 'Number of generated case suppliers does not match number of framework lot suppliers');
    }
}