force-app/main/default/objects/Procurement_Stage__c/Procurement_Stage__c.object-meta.xml
<CustomObject>
    <label>Procurement Stage</label>
    <nameField>
        <label>Stage</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procurement Stages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Procurement_Stage__c/fields/Procurement__c.field-meta.xml
<CustomField>
    <fullName>Procurement__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Procurement Stages</relationshipLabel>
    <relationshipName>Procurement_Stages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Procurement_Stage__c/fields/Seq__c.field-meta.xml
<CustomField>
    <fullName>Seq__c</fullName>
    <inlineHelpText>Provides the unique sequence for the specific stage within the procurement process</inlineHelpText>
    <label>Seq</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ProcurmentStagePreventDeletionTest.cls
@isTest
private class ProcurmentStagePreventDeletionTest {

  static final String ORG_NAME = 'Test Org';
  
  static testmethod void testPreventPsDel()
  {
    // create custom settings
    insert UnitTestHelper.createOpsWorkflowStages();
    insert UnitTestHelper.createOpsWorkflowTemplates();
    
    Account org = UnitTestHelper.createOrganisationAccount(ORG_NAME);
    insert org;
    Case c = UnitTestHelper.createProcurementCase(org.id);
    insert c;
      
        Procurement_Stage__c psRecord = new Procurement_Stage__c(Procurement__c= c.Id, name='ITT Live', Seq__c=40);
        insert psRecord;
        
        try{
            delete psRecord;
        }catch(DMLexception e){
            system.assert(e.getMessage().contains('You can not delete ITT Live from a Procurement'),'You can not delete ITT Live from a Procurement');                       
        }
    }
}