force-app/main/default/objects/Customer_Delay__c/Customer_Delay__c.object-meta.xml
<CustomObject>
    <description>US547</description>
    <label>Customer Delay</label>
    <nameField>
        <displayFormat>CD-{000000}</displayFormat>
        <label>Customer Delay ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Delays</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Delay__c/fields/Customer_Delay_Reason__c.field-meta.xml
<CustomField>
    <fullName>Customer_Delay_Reason__c</fullName>
    <description>US547</description>
    <label>Customer Delay Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer_Requires_Additional_Approvals</fullName>
                <label>Customer Requires Additional Approvals</label>
            </value>
            <value>
                <fullName>Customer_Unavailable</fullName>
                <label>Customer Unavailable</label>
            </value>
            <value>
                <fullName>Customer_Missed_Deadline</fullName>
                <label>Customer Missed Deadline</label>
            </value>
            <value>
                <fullName>Customer_Requested_Delay</fullName>
                <label>Customer Requested Delay</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Delay__c/fields/Duration_Days__c.field-meta.xml
<CustomField>
    <fullName>Duration_Days__c</fullName>
    <description>US547</description>
    <label>Duration (Days)</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Delay__c/fields/Duration_Hours__c.field-meta.xml
<CustomField>
    <fullName>Duration_Hours__c</fullName>
    <description>US547</description>
    <label>Duration (Hours)</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer_Delay__c/fields/Procurement__c.field-meta.xml
<CustomField>
    <fullName>Procurement__c</fullName>
    <description>US547</description>
    <label>Procurement</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Customer Delays</relationshipLabel>
    <relationshipName>Customer_Delays</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Customer_Delay__c/fields/Start_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Start_DateTime__c</fullName>
    <description>US547</description>
    <label>Start DateTime</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Customer_Delay__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>US547</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Delay__c/fields/Stop_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Stop_DateTime__c</fullName>
    <description>US547</description>
    <label>Stop DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/CustomerDelayTrigger_Test.cls
@isTest
public class CustomerDelayTrigger_Test {
    
    static testMethod void validateCustomerDelay(){   
        
        //New Test Account
        Account acc = new Account(Name = 'New Test Account', Sector__c = 'Wider Public Sector', Status__c = 'Active');
        
        insert acc;

        Contact con = new Contact(FirstName = 'Amorous', LastName = 'Aardvark', Email = 'tristam.hardman@crowncommercial.gov.uk', AccountID = acc.ID );
        
        insert con;
        
        Case cas = new Case(ContactID = con.ID, AccountID = acc.ID, Status = 'In Progress');  //Status is newly added to test
        
        insert cas;
        
        //Create a new Customer Delay
        Customer_Delay__c cusdel1 = new Customer_Delay__c();
        cusdel1.Procurement__c = cas.ID;
        cusdel1.Start_DateTime__c = DateTime.newInstance(2018,11,7,0,0,0); //A Wednesday
        insert cusdel1;
        
        
        //The newly create Customer Delay only has a Start_DateTime - so the Duration should still be NULL.
        cusdel1 = [SELECT Start_DateTime__c, Stop_DateTime__c, Duration_Days__c, Duration_Hours__c FROM Customer_Delay__c WHERE ID =:cusdel1.ID ];
        system.debug(cusdel1.Start_DateTime__c);
        system.debug(cusdel1.Stop_DateTime__c);
        system.debug(cusdel1.Duration_Days__c);
        system.assertEquals(cusdel1.Duration_Days__c, NULL);
        system.assertEquals(cusdel1.Duration_Hours__c, NULL);
        
        //Now update the Stop_DateTime - this should cause the Trigger to calculate the Duration fields.
        //Customer Delay must also be closed - There is a Validation that prevents a Stop Date being populated unless Status is closed.
        cusdel1.Stop_DateTime__c = DateTime.newInstance(2018,11,14,0,0,0); //One calendar week later = 5 working days = 40 working hours
        cusdel1.Status__c = 'Closed';
        cusdel1.Customer_Delay_Reason__c = 'Customer_Unavailable'; //Added due to failure found when deploying to QA
        
        update cusdel1;
        
        cusdel1 = [SELECT Start_DateTime__c, Stop_DateTime__c, Duration_Days__c, Duration_Hours__c FROM Customer_Delay__c WHERE ID =:cusdel1.ID ];
        
        system.debug(cusdel1.Start_DateTime__c);
        system.debug(cusdel1.Stop_DateTime__c);
        system.debug(cusdel1.Duration_Days__c);
        system.assertEquals(cusdel1.Duration_Days__c, 5);
        system.assertEquals(cusdel1.Duration_Hours__c, 40);
         
        
        //Now update both the Start_DateTime and Stop_DateTime and check that the Durations recalculate correctly
        cusdel1.Start_DateTime__c = DateTime.newInstance(2018,11,8,0,0,0); //A Thursday
        cusdel1.Stop_DateTime__c = DateTime.newInstance(2018,11,22,0,0,0); //Two calendars week later = 10 working days = 80 working hours
        
        update cusdel1;
        
        cusdel1 = [SELECT Start_DateTime__c, Stop_DateTime__c, Duration_Days__c, Duration_Hours__c FROM Customer_Delay__c WHERE ID =:cusdel1.ID ];
        
        system.debug(cusdel1.Start_DateTime__c);
        system.debug(cusdel1.Stop_DateTime__c);
        system.debug(cusdel1.Duration_Days__c);
        system.assertEquals(cusdel1.Duration_Days__c, 10);
        system.assertEquals(cusdel1.Duration_Hours__c, 80);
        
        
        //Now create another customer delay, but this time with both Start_DateTime and Stop_Date populated from the outset
        //This would only happen if the user used "New" button (which will be hidden) or "Save & New" (which cannot be hidden)
        //This will test the 'Insert' element of the Trigger
        Customer_Delay__c cusdel2 = new Customer_Delay__c();
        cusdel2.Procurement__c = cas.ID;  //Status of cusdel1 is closed
        cusdel2.Start_DateTime__c = DateTime.newInstance(2018,11,8,0,0,0); //A Thursday
        cusdel2.Stop_DateTime__c = DateTime.newInstance(2018,11,22,0,0,0); //Two calendars week later = 10 working days = 80 working hours
        cusdel2.Status__c = 'Closed';
        cusdel2.Customer_Delay_Reason__c = 'Customer_Unavailable'; //Added due to failure found when deploying to QA
        
        insert cusdel2;
        
        cusdel2 = [SELECT Start_DateTime__c, Stop_DateTime__c, Duration_Days__c, Duration_Hours__c FROM Customer_Delay__c WHERE ID =:cusdel2.ID ];
      
        system.debug(cusdel2.Start_DateTime__c);
        system.debug(cusdel2.Stop_DateTime__c);
        system.debug(cusdel2.Duration_Days__c);
        system.assertEquals(cusdel2.Duration_Days__c, 10);
        system.assertEquals(cusdel2.Duration_Hours__c, 80);
    }

}