force-app/main/default/objects/Opportunity_Monthly_Value__c/Opportunity_Monthly_Value__c.object-meta.xml
<CustomObject>
    <label>Opportunity Monthly Value</label>
    <nameField>
        <displayFormat>OMV - {0000}</displayFormat>
        <label>Opportunity Monthly Value ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Monthly Value</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Monthly_Value__c/fields/Monthly_Value__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Value__c</fullName>
    <label>Monthly Value</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_Monthly_Value__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Monthly Value</relationshipLabel>
    <relationshipName>Opportunity_Monthly_Value</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/OpportunityService.cls
public with sharing class OpportunityService {
    public static boolean isRunning = false;
    public static boolean isValidForMonthly(Opportunity newOpp, Opportunity oldOpp){
        boolean isAllNotNull = (newOpp.CloseDate != null && newOpp.Contract_Close_Date__c != null && newOpp.Amount != null);
        if(oldOpp != null && !newOpp.Parent_Opportunity__c && newOpp.Parent_Opportunity__c != oldOpp.Parent_Opportunity__c && isAllNotNull){
            return true;
        }
        if(newOpp.CloseDate == null || newOpp.Contract_Close_Date__c == null || newOpp.Amount == null ){
            return false;
        }else if(oldOpp != null && newOpp.CloseDate == oldOpp.CloseDate && newOpp.Contract_Close_Date__c == oldOpp.Contract_Close_Date__c && newOpp.Amount == oldOpp.Amount ){
            return false;
        }
        return true;
    }
    public static void createMonthlyRecords(List<Opportunity> oppList){
        List<Opportunity_Monthly_Value__c> annualValueListToInsert = new List<Opportunity_Monthly_Value__c>();
        for(Opportunity opp: oppList){
            Integer monthDiff = opp.CloseDate.monthsBetween(opp.Contract_Close_Date__c);
            //if (opp.CloseDate.day() >= opp.Contract_Close_Date__c.day()) 
                monthDiff++;
            Decimal AmountToDevide = opp.Amount/monthDiff;
            Opportunity_Monthly_Value__c av = new Opportunity_Monthly_Value__c();
            for( Integer i = 0; i < monthDiff; i++){
                av.Opportunity__c = opp.Id;
                
                av.Monthly_Value__c = AmountToDevide;
                /*if(i == monthDiff && opp.CloseDate.addMonths(i) > opp.Contract_Close_Date__c){
                    av.Date__c = opp.Contract_Close_Date__c;
                }else{
                	av.Date__c = opp.CloseDate.addMonths(i);    
                }*/
                av.Date__c = date.newInstance(opp.CloseDate.addMonths(i).Year(), opp.CloseDate.addMonths(i).Month(), 1);
                annualValueListToInsert.add(av);
                av = new Opportunity_Monthly_Value__c();
                
            }
            System.debug(monthDiff);
        }
        if(annualValueListToInsert.size() > 0){
            try{
            	insert annualValueListToInsert;
        	}catch(exception e){}
        
            
        }
    }
    public static boolean DeleteMonthly(Opportunity newOpp){
        if(newOpp.CloseDate == null || newOpp.Contract_Close_Date__c == null || newOpp.Amount == null ){
        	return true;
        }
        return false;
    }
    public static void CreateMonthlyValues(List<Opportunity> newMapOpps, Map<Id,Opportunity> oldMapOpps){
        List<Opportunity> tempOpps = new List<Opportunity>();
        Boolean isOldMap = (oldMapOpps == null ? false: true);
        Set<Id> oppIDS = new Set<Id>();
        for(Opportunity opp: newMapOpps){
            if(opp.Parent_Opportunity__c){
                oppIDS.add(opp.ID);
            }else{
            	if(isOldMap){
                    if(isValidForMonthly(opp, oldMapOpps.get(opp.Id))){
                        tempOpps.add(opp);
                        oppIDS.add(opp.ID);
                    }
                    if(DeleteMonthly(opp)){
                        oppIDS.add(opp.ID);
                    }
                }else{
                    if(isValidForMonthly(opp, null)){
                        tempOpps.add(opp);
                        
                    }    
                }    
            }
            
            
        }
        
        if(isOldMap && oppIDS.size() > 0){
            deleteMonthlyFromOpp( oppIDS);
        }
        
        if(tempOpps.size() > 0){ 
            createMonthlyRecords(tempOpps); 
        }
    }
    public static void deleteMonthlyFromOpp(set<Id> oppIDS){
        List<Opportunity_Monthly_Value__c> listMonthlyOpp = [Select id from Opportunity_Monthly_Value__c where Opportunity__c In: oppIDS];
        
        try{
            if(listMonthlyOpp.size() > 0){
            	Delete listMonthlyOpp;        
            }
        	
        }catch(exception e){
            system.debug('Error Message On Delete OMV ' + e.getMessage());
        }
        
    }
}