force-app/main/default/objects/Org_Settings__c/Org_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Global settings used to control the active state of custom logic defined within the org.</description>
    <label>Org Settings</label>
</CustomObject>

force-app/main/default/objects/Org_Settings__c/fields/PEM_SSO_Only__c.field-meta.xml
<CustomField>
    <fullName>PEM_SSO_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <description>SSO only, limited access to SSO only</description>
    <inlineHelpText>SSO only, limited access to SSO only</inlineHelpText>
    <label>PEM SSO Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PEM_Profile_CC.cls
/*********************************************************************
Name:  PEM_Profile_CC
Copyright © 2016  Salesforce
=====================================================================

Purpose: This class acts as the controller for the Profile Menu and User Profile Component.

=====================================================================
History
-------
VERSION  AUTHOR            DATE         DETAIL                      Description
 1.0    Steve O'Halloran   2016-11-11   Initial version
*********************************************************************/
public with sharing class PEM_Profile_CC {

    public class UserWrapper {
        @AuraEnabled public User user;
        @AuraEnabled public boolean SSOOnly;
    }
    
    @AuraEnabled
    public static UserWrapper getUserWrapper() {
        boolean SSOOnly = Org_Settings__c.getInstance().PEM_SSO_Only__c;
        User u = [SELECT Id, Name, SmallPhotoUrl, UserType
                  FROM 
                  User
                  WHERE Id = :UserInfo.getUserId()];
        UserWrapper uw = new UserWrapper();
        uw.user = u;
        uw.SSOOnly = SSOOnly;
        return uw;
    }
    
    
	@AuraEnabled
	public static User getUserInfo() {
		return [SELECT Id, Name, SmallPhotoUrl, UserType
			FROM 
				User
			WHERE Id = :UserInfo.getUserId()]; 
	}
}