force-app/main/default/objects/Exception_Log__c/Exception_Log__c.object-meta.xml
<CustomObject>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>EL-{00000000}</displayFormat>
        <label>Exception Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exceptions Log</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Exception_Log__c/fields/Running_User__c.field-meta.xml
<CustomField>
    <fullName>Running_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Running User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>IPM_Exception_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Framework__c/Master_Framework__c.object-meta.xml
<CustomObject>
    <description>This object represents Framework related to Opportunity, Enquiry, and Category.</description>
    <label>Framework</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Frameworks</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Organisation_Framework__c/Organisation_Framework__c.object-meta.xml
<CustomObject>
    <description>Junction object to connect Organisation (Account) and Framework - replaces Framework Interests picklist on Account</description>
    <label>Framework Interest</label>
    <nameField>
        <displayFormat>OF-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Framework Interests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Organisation_Framework__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Organisation_Framework__c/fields/Framework__c.field-meta.xml
<CustomField>
    <fullName>Framework__c</fullName>
    <label>Framework</label>
    <referenceTo>Master_Framework__c</referenceTo>
    <relationshipName>Organisation_Frameworks</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Organisation_Framework__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <label>Organisation</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Organisation_Frameworks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/FrameworkInterestGenerator_Batch_Test.cls
/*********************************************************************
 Name:  FrameworkInterestGenerator_Batch_Test
 Copyright © 2016  Salesforce
 ======================================================
 ======================================================
 Purpose: Test class for FrameworkInterestGenerator_Batch
		ATTENTION! ONE TIME DATA FIX, CAN BE DELETED AFTER USE
 ======================================================
 ======================================================
 History                                                            
 -------                                                            
 VERSION  AUTHOR            DATE             DETAIL             Description
		1.0  Cezary Zeleznicki  2016-12-12     Initial version
 *********************************************************************/
@isTest
private class FrameworkInterestGenerator_Batch_Test {
	private final static List<String> frameworkNames = new List<String>{
		'Advertising Agencies',
		'Agency Nurses and Social Workers',
		'Agile Route to Market',
		'Allied Health Professionals/Health Science Service',
		'Allied Health Professionals and Health Science Services Staff',
		'Assistive Technologies-Telecare Telehealth Telecoaching',
		'Automatic Meter Reading (AMR)',
		'Behavioural Insights Consulting and Research',
		'Central Government Travel Management Service',
		'Cipher - Consultancy Services Framework',
		'Civil Service Learning'
	};

	@testSetup
	static void createData() {
		List<Master_Framework__c> frameworks = new List<Master_Framework__c>();
		for(Integer i = 0; i < 10; i++) {
			Master_Framework__c mf = UnitTestDataFactory.createMasterFramework();
			mf.Name = frameworkNames[i];
			frameworks.add(mf);
		}
		insert frameworks;

		frameworkNames.remove(frameworkNames.size()-1);
		List<Account> accounts = new List<Account>();
		for(Integer i = 0; i < 50; i++) {
			Account org = UnitTestHelper.createOrganisationAccount('Test Organisation ' + i);
			org.Framework_Interest__c = String.join(frameworkNames, ';');
			accounts.add(org);
		}
		
		insert accounts;
	}

	static testMethod void execute_Test() {
		Test.startTest();
		FrameworkInterestGenerator_Batch crtu = new FrameworkInterestGenerator_Batch();
		Database.executeBatch(crtu);
		Test.stopTest();

		List<Account> accounts = [
			SELECT Id, Framework_Interest__c,
				(SELECT Id, Organisation__c, Framework__c, Framework__r.Name, Comments__c FROM Organisation_Frameworks__r)
			FROM Account
				WHERE RecordType.DeveloperName = 'Organisation'
					AND Framework_Interest__c != null
		];

		for(Account a : accounts) {
			System.assertEquals(10, a.Organisation_Frameworks__r.size(), '10 Organisation Frameworks should be created');
			for(Organisation_Framework__c orgFramework : a.Organisation_Frameworks__r) {
				System.assert(a.Framework_Interest__c.contains(orgFramework.Framework__r.Name), 
					'Organisation Framework should created for each value in Framework Interest picklist');
			}
		}

		List<Note> notes = [
			SELECT Id, ParentId, Body, Title
			FROM Note
				WHERE ParentId IN : accounts
		];
		System.assertEquals(accounts.size(), notes.size(), 'There should be one note added per Organisation\'s ' +
			'successfull Organisation Framework insertions');
	}

	static testMethod void execute_FrameworkMissing() {
		Account a = [SELECT Id, Framework_Interest__c
			FROM Account
				WHERE RecordType.DeveloperName = 'Organisation'
					AND Framework_Interest__c != null
				LIMIT 1
		];

		a.Framework_Interest__c += ';' + frameworkNames[10];
		update a;

		Test.startTest();
		FrameworkInterestGenerator_Batch crtu = new FrameworkInterestGenerator_Batch();
		Database.executeBatch(crtu);
		Test.stopTest();

		a = [
			SELECT Id, Framework_Interest__c,
				(SELECT Id, Organisation__c, Framework__c, Framework__r.Name, Comments__c FROM Organisation_Frameworks__r)
			FROM Account
				WHERE Id = :a.Id
		];

		System.assertEquals(10, a.Organisation_Frameworks__r.size(), '10 Organisation Frameworks should be created');

		List<String> fNames = a.Framework_Interest__c.split(';');
		for(Organisation_Framework__c orgFramework : a.Organisation_Frameworks__r) {
			for(Integer i = 0; i < fNames.size(); i++) {
				if(fNames[i] != orgFramework.Framework__r.Name) {
					continue;
				}
				fNames.remove(i);
			}
		}

		System.assertEquals(1, fNames.size(), 
			'One picklist value doesn\'t have matching Framework so Organisation Framework should be missing');

		List<Note> notes = [
			SELECT Id, ParentId, Body, Title
			FROM Note
				WHERE ParentId = :a.Id
		];
		System.assertEquals(2, notes.size(), 'There should be two notes added ' +
			'one for matching frameworks and another for not matching');
		Boolean isNotMatchedNoteAdded = false;
		for(Note n : notes) {
			if(n.Title.contains('NOT MATCHED')) {
				isNotMatchedNoteAdded = true;
			}
		}
		System.assert(isNotMatchedNoteAdded, 'Note for not matched record should be added');
	}

	static testMethod void execute_Error() {
		Master_Framework__c mf = [SELECT Id FROM Master_Framework__c LIMIT 1];
		Account a = [SELECT Id FROM Account LIMIT 1];
		delete mf;
		Organisation_Framework__c orgFramework = new Organisation_Framework__c(Organisation__c = a.Id,
			Framework__c = mf.Id);

		Test.startTest();
		FrameworkInterestGenerator_Batch crtu = new FrameworkInterestGenerator_Batch();
		crtu.orgFrameworks.add(orgFramework);
		Database.executeBatch(crtu);
		Test.stopTest();

		List<Exception_Log__c> exceptionLogs = [
			SELECT Id, Class_Name__c, Method_Name__c 
			FROM Exception_Log__c
			WHERE Running_User__c =: UserInfo.getUserId()
		];
		for(Exception_Log__c el : exceptionLogs) {
			System.assertEquals(FrameworkInterestGenerator_Batch.class.toString(), el.Class_Name__c, 
				'Exception should be generated by Batch Class');
		}
	}

	static testMethod void test_Schedulable() {
		String cronExp = '0 0 0 15 3 ? 2030';

		Test.startTest();
		String jobId = System.schedule('ScheduleApexClassTest',
			cronExp, new FrameworkInterestGenerator_Batch());

		CronTrigger ct = [
			SELECT Id, CronExpression, TimesTriggered, NextFireTime
			FROM CronTrigger WHERE id = :jobId
		];
		Test.stopTest();

		System.assertEquals(cronExp, ct.CronExpression, 'Cron expression should be correctly added');
		System.assertEquals(0, ct.TimesTriggered, 'Job shoul not be executed before stop test');
		System.assertEquals('2030-03-15 00:00:00', String.valueOf(ct.NextFireTime), 
			'Next time job should be run should match the date from cron expression');
	 }
}