force-app/main/default/objects/Exception_Log__c/Exception_Log__c.object-meta.xml
<CustomObject>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>EL-{00000000}</displayFormat>
        <label>Exception Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exceptions Log</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Exception_Log__c/fields/Application_Name__c.field-meta.xml
<CustomField>
    <fullName>Application_Name__c</fullName>
    <label>Application Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unilever IPM NG</fullName>
                <default>true</default>
                <label>Unilever IPM NG</label>
            </value>
            <value>
                <fullName>Unilever Agencies</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/DebugLevel__c.field-meta.xml
<CustomField>
    <fullName>DebugLevel__c</fullName>
    <label>DebugLevel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
                <default>true</default>
                <label>Error</label>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Debug</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/IntegrationPayload__c.field-meta.xml
<CustomField>
    <fullName>IntegrationPayload__c</fullName>
    <description>If log is integration related show payload</description>
    <label>IntegrationPayload</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/LogCode__c.field-meta.xml
<CustomField>
    <fullName>LogCode__c</fullName>
    <label>LogCode</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/ReferenceId__c.field-meta.xml
<CustomField>
    <fullName>ReferenceId__c</fullName>
    <description>The related record id</description>
    <label>ReferenceId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/ReferenceInfo__c.field-meta.xml
<CustomField>
    <fullName>ReferenceInfo__c</fullName>
    <description>The related record info</description>
    <label>ReferenceInfo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/Running_User__c.field-meta.xml
<CustomField>
    <fullName>Running_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Running User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>IPM_Exception_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/StackTrace_Message__c.field-meta.xml
<CustomField>
    <fullName>StackTrace_Message__c</fullName>
    <label>StackTrace Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/Timer__c.field-meta.xml
<CustomField>
    <fullName>Timer__c</fullName>
    <label>Timer</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ExceptionLoggingHelper.cls
/*****************************************************************************************************************************
Name: ExceptionLoggingHelper

Purpose: Utilty class for logging errors

History
-------
VERSION AUTHOR                          DATE            DETAIL  FEATURES/CSR/TTP
1.0 -   pczechumski@salesforce.com      07/03/2016      INITIAL DEVELOPMENT
*******************************************************************************************************************************/

global without sharing class ExceptionLoggingHelper {
	
	public static final String EXCEPTION_LOGGER_DEFAULT_APP_NAME = 'CCS';

	private static List<Exception_Log__c> exceptionlogList {get;set;}

	public static void createErrorLog(String runninguserId, String className,String methodName,String exMsg, Exception exceptionOccured, 
                                            String debugLevel, String integrationPayload, String referenceInfo, Integer timer, String applicationName){
        
        processExceptionLog(runninguserId,className,methodName,exMsg,exceptionOccured,debugLevel,integrationPayload,referenceInfo,timer,applicationName);       
    }
    
    private static void processExceptionLog(String runninguserId, String className,String methodName,String exMsg, Exception exceptionOccured, 
                                            String debugLevel, String integrationPayload,String referenceInfo, Integer timer, String applicationName)
    {
        String referenceId = null;
        String logCode = null;
        
        if(applicationName == null){
            applicationName = EXCEPTION_LOGGER_DEFAULT_APP_NAME;
        }
        
        if(exceptionlogList == null){
            exceptionlogList = new List<Exception_Log__c>();
        }                
        
        if(exceptionOccured != null && exceptionOccured.getTypeName() == 'System.DmlException'){
            referenceId = exceptionOccured.getDmlId(0);
            logCode = string.valueOf(exceptionOccured.getDmlType(0));
        }
        
        //skip log insertion if exception occured in constructor, as @future and DML operations are not allowed in constructor. 
        if(exceptionOccured != null && className != methodName){
            exceptionlogList.add(createObjectData(runninguserId,className,methodName,exMsg,exceptionOccured.getTypeName(),exceptionOccured.getStackTraceString(),logCode,debugLevel,integrationPayload,referenceId,referenceInfo,timer,applicationName));
        }
                
        if(Limits.getLimitDMLStatements() < 1){
            System.debug('*********No Of DML Statement Limit Reached.********');        
        }      
        else{  
            try{ 
                if(!Trigger.isExecuting){
                    // In case it is not invoked from trigger, make asyncronous call and create Exception Record.
                    if(!System.isFuture() && !System.isBatch() && Limits.getFutureCalls() < 1){
                        //skip log insertion if exception occured in constructor, as @future and DML operations are not allowed in constructor. 
                        if(className != methodName){
                            insertExceptionInFuture(runninguserId,className,methodName,exMsg,exceptionOccured.getTypeName(),exceptionOccured.getStackTraceString(),logCode,debugLevel,integrationPayload,referenceId,referenceInfo,timer,applicationName);
                        }
                    }
                    else{
                        //skip log insertion if exception occured in constructor, as DML operations are not allowed in constructor. 
                        if(className != methodName){
                            List<Exception_Log__c> exceptionList = new List<Exception_Log__c>{ createObjectData(runninguserId,className,methodName,exMsg,exceptionOccured.getTypeName(),exceptionOccured.getStackTraceString(),logCode,debugLevel,integrationPayload,referenceId,referenceInfo,timer,applicationName)};
                            insert exceptionList;
                        }                   
                    }
                }
            }
            catch(exception ex){
                System.debug('*********Exception in Logger Class ********'+ex.getMessage());
                insert exceptionlogList;
            }              
        }
    }
    
    @future
    public static void insertExceptionInFuture(String runninguserId, String className,String methodName,String exMsg, String execptionType, String stackTrace, String logCode,  
                                            String debugLevel, String integrationPayload, String referenceId, String referenceInfo, Integer timer, String applicationName)
    {
        List<Exception_Log__c> exceptionList = new List<Exception_Log__c>{ createObjectData(runninguserId,className,methodName,exMsg,execptionType,stackTrace,logCode,debugLevel,integrationPayload,referenceId,referenceInfo,timer,applicationName)};
        insert exceptionList;
    }
    
    private static Exception_Log__c createObjectData(String runninguserId, String className,String methodName,String exMsg, String exceptionType, String stackTrace, String logCode, 
                                            String debugLevel, String integrationPayload, String referenceId, String referenceInfo, Integer timer, String applicationName)
    {
        Exception_Log__c exceptionLog = new Exception_Log__c();
        exceptionLog.Running_User__c = runninguserId;
        exceptionLog.Class_Name__c = className;
        exceptionLog.Method_Name__c = methodName;
        exceptionLog.Exception_Message__c = exMsg;            
        exceptionLog.Exception_Type__c= exceptionType;
        exceptionLog.StackTrace_Message__c = stackTrace;
        exceptionLog.LogCode__c = logCode;
        exceptionLog.DebugLevel__c = debugLevel;
        exceptionLog.IntegrationPayload__c = integrationPayload;
        exceptionLog.ReferenceId__c = referenceId;
        exceptionLog.ReferenceInfo__c = referenceInfo;
        exceptionLog.Timer__c = timer;
        exceptionLog.Application_Name__c = applicationName;
        return exceptionLog;
    }
}