force-app/main/default/objects/Framework_Forecast__c/Framework_Forecast__c.object-meta.xml
<CustomObject>
    <description>Umbrella record to hold all forecast figures for a given FY</description>
    <label>Framework Forecast</label>
    <nameField>
        <displayFormat>FF{000000}</displayFormat>
        <label>Forecast #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Framework Forecasts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Framework_Forecast__c/fields/Framework__c.field-meta.xml
<CustomField>
    <fullName>Framework__c</fullName>
    <label>Framework</label>
    <referenceTo>Master_Framework__c</referenceTo>
    <relationshipLabel>Framework Forecasts</relationshipLabel>
    <relationshipName>Framework_Forecasts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/Framework_Forecast_Year__c.object-meta.xml
<CustomObject>
    <description>Holds forecast information for relative future years for a given financial year</description>
    <label>Framework Forecast Year</label>
    <nameField>
        <displayFormat>FR{000000}</displayFormat>
        <label>Forecast Year #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Framework Forecast Years</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/Acknowledged_Annual__c.field-meta.xml
<CustomField>
    <fullName>Acknowledged_Annual__c</fullName>
    <label>Acknowledged Annual</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/Acknowledged_M01__c.field-meta.xml
<CustomField>
    <fullName>Acknowledged_M01__c</fullName>
    <label>Acknowledged M01</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/Acknowledged_M02__c.field-meta.xml
<CustomField>
    <fullName>Acknowledged_M02__c</fullName>
    <label>Acknowledged M02</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/Acknowledged_M03__c.field-meta.xml
<CustomField>
    <fullName>Acknowledged_M03__c</fullName>
    <label>Acknowledged M03</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/Acknowledged_M04__c.field-meta.xml
<CustomField>
    <fullName>Acknowledged_M04__c</fullName>
    <label>Acknowledged M04</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/Acknowledged_M05__c.field-meta.xml
<CustomField>
    <fullName>Acknowledged_M05__c</fullName>
    <label>Acknowledged M05</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/Acknowledged_M06__c.field-meta.xml
<CustomField>
    <fullName>Acknowledged_M06__c</fullName>
    <label>Acknowledged M06</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/Acknowledged_M07__c.field-meta.xml
<CustomField>
    <fullName>Acknowledged_M07__c</fullName>
    <label>Acknowledged M07</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/Acknowledged_M08__c.field-meta.xml
<CustomField>
    <fullName>Acknowledged_M08__c</fullName>
    <label>Acknowledged M08</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/Acknowledged_M09__c.field-meta.xml
<CustomField>
    <fullName>Acknowledged_M09__c</fullName>
    <label>Acknowledged M09</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/Acknowledged_M10__c.field-meta.xml
<CustomField>
    <fullName>Acknowledged_M10__c</fullName>
    <label>Acknowledged M10</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/Acknowledged_M11__c.field-meta.xml
<CustomField>
    <fullName>Acknowledged_M11__c</fullName>
    <label>Acknowledged M11</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/Acknowledged_M12__c.field-meta.xml
<CustomField>
    <fullName>Acknowledged_M12__c</fullName>
    <label>Acknowledged M12</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/Acknowledged_Q1__c.field-meta.xml
<CustomField>
    <fullName>Acknowledged_Q1__c</fullName>
    <label>Acknowledged Q1</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/Acknowledged_Q2__c.field-meta.xml
<CustomField>
    <fullName>Acknowledged_Q2__c</fullName>
    <label>Acknowledged Q2</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/Acknowledged_Q3__c.field-meta.xml
<CustomField>
    <fullName>Acknowledged_Q3__c</fullName>
    <label>Acknowledged Q3</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/Acknowledged_Q4__c.field-meta.xml
<CustomField>
    <fullName>Acknowledged_Q4__c</fullName>
    <label>Acknowledged Q4</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/Actual_Forecast_Year__c.field-meta.xml
<CustomField>
    <fullName>Actual_Forecast_Year__c</fullName>
    <formula>&quot;20&quot; + TEXT(Value(MID(Business_Plan_Year__c,3,2)) + Value(RIGHT(TEXT(Relative_Forecast_Year__c),1)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Actual Forecast Year</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/Annual__c.field-meta.xml
<CustomField>
    <fullName>Annual__c</fullName>
    <label>Annual</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/Forecast__c.field-meta.xml
<CustomField>
    <fullName>Forecast__c</fullName>
    <label>Forecast #</label>
    <referenceTo>Framework_Forecast__c</referenceTo>
    <relationshipLabel>Framework Forecast Years</relationshipLabel>
    <relationshipName>Framework_Forecast_Years</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/Last_Acknowledged_By__c.field-meta.xml
<CustomField>
    <fullName>Last_Acknowledged_By__c</fullName>
    <label>Last Acknowledged By</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/Last_Acknowledged_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Acknowledged_Date__c</fullName>
    <label>Last Acknowledged Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/M01__c.field-meta.xml
<CustomField>
    <fullName>M01__c</fullName>
    <label>M01</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/M02__c.field-meta.xml
<CustomField>
    <fullName>M02__c</fullName>
    <label>M02</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/M03__c.field-meta.xml
<CustomField>
    <fullName>M03__c</fullName>
    <label>M03</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/M04__c.field-meta.xml
<CustomField>
    <fullName>M04__c</fullName>
    <label>M04</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/M05__c.field-meta.xml
<CustomField>
    <fullName>M05__c</fullName>
    <label>M05</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/M06__c.field-meta.xml
<CustomField>
    <fullName>M06__c</fullName>
    <label>M06</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/M07__c.field-meta.xml
<CustomField>
    <fullName>M07__c</fullName>
    <label>M07</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/M08__c.field-meta.xml
<CustomField>
    <fullName>M08__c</fullName>
    <label>M08</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/M09__c.field-meta.xml
<CustomField>
    <fullName>M09__c</fullName>
    <label>M09</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/M10__c.field-meta.xml
<CustomField>
    <fullName>M10__c</fullName>
    <label>M10</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/M11__c.field-meta.xml
<CustomField>
    <fullName>M11__c</fullName>
    <label>M11</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/M12__c.field-meta.xml
<CustomField>
    <fullName>M12__c</fullName>
    <label>M12</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/Q1__c.field-meta.xml
<CustomField>
    <fullName>Q1__c</fullName>
    <label>Q1</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/Q2__c.field-meta.xml
<CustomField>
    <fullName>Q2__c</fullName>
    <label>Q2</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/Q3__c.field-meta.xml
<CustomField>
    <fullName>Q3__c</fullName>
    <label>Q3</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/Q4__c.field-meta.xml
<CustomField>
    <fullName>Q4__c</fullName>
    <label>Q4</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/Relative_Forecast_Year__c.field-meta.xml
<CustomField>
    <fullName>Relative_Forecast_Year__c</fullName>
    <label>Relative Forecast Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Year 0</fullName>
            </value>
            <value>
                <fullName>Year 1</fullName>
            </value>
            <value>
                <fullName>Year 2</fullName>
            </value>
            <value>
                <fullName>Year 3</fullName>
            </value>
            <value>
                <fullName>Year 4</fullName>
            </value>
            <value>
                <fullName>Year 5</fullName>
                <isActive>false</isActive>
                <label>Year 5</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/Sector__c.field-meta.xml
<CustomField>
    <fullName>Sector__c</fullName>
    <label>Sector</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CG</fullName>
            </value>
            <value>
                <fullName>WPS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/recordTypes/Live.recordType-meta.xml
<RecordType>
    <fullName>Live</fullName>
    <active>true</active>
    <label>Live</label>
</RecordType>

force-app/main/default/objects/Master_Framework__c/Master_Framework__c.object-meta.xml
<CustomObject>
    <description>This object represents Framework related to Opportunity, Enquiry, and Category.</description>
    <label>Framework</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Frameworks</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/bg_FrameworkForecastViewController.cls
/*********************************************************************
 Name:  bg_FrameworkForecastViewController
 History                                                            
 -------                                                            
 VERSION  AUTHOR            DATE             DETAIL             Description
   1.0   Jorge Delgado      2017-08-09       Initial version
   1.1   James Burgess      2017-09-12       Case 00030836      Update to model to view years by sector and improved error handling
   1.2   Conor Spark        2017-10-18       Case 00033037      Added totals for years, frameworks, sectors and overall
 *********************************************************************/
public with sharing class bg_FrameworkForecastViewController {

    public String acknowledgedForecastYearId { get; set; }
    public Map<String, List<ForecastYearStyleWrapper>> wpsForecastYearByBY {get; set;} //Wider-public Sector
    public Map<String, List<ForecastYearStyleWrapper>> cgForecastYearByBY {get; set;} //Central Government

    public List<String> businessYears;
    public Map<String, Decimal> yearTotalsDec{get; set;}
    public Map<String, String> yearTotals{get; set;}
    public Map<String, Decimal> cgTotalsDec{get; set;}
    public Map<String, String> cgTotals{get; set;}
    public Map<String, Decimal> wpsTotalsDec{get; set;}
    public Map<String, String> wpsTotals{get; set;}
    public List<Decimal> yearTotalsListDec {get; set;}
    public List<String> yearTotalsList {get; set;}
    public String overallTotal {get; set;}
    public Decimal overallTotalDec {get; set;}
    public String listViewId;
    public ApexPages.StandardSetController frameworkSetController;

    private Map<Id, Framework_Forecast_Year__c> forecastYearMapInMemory;
    private List<Framework_Forecast_Year__c> cachedForecastYears;
    private Set<Id> frameworkIds;

    /*
    *   Constructor, empty for the moment
    */
    public bg_FrameworkForecastViewController(ApexPages.StandardSetController controller) {

    }

    /*
    *   Getter method sets up set controller
    */
    public ApexPages.StandardSetController GetFrameworkSetController()
    {
        if (frameworkSetController == null)
        {
            frameworkSetController = new ApexPages.StandardSetController([SELECT Name FROM Framework_Forecast__c]);
            frameworkSetController.setFilterId(GetListViewId());
        }
        return frameworkSetController;
    }


    /*
    *   Getter and setter methods for listViewId
    */
    public String GetListViewId()
    {
        if (listViewId == null)
        {
            listViewId = frameworkSetController.getListViewOptions().get(0).getValue();
        }
        return listViewId;
    }

    public void SetListViewId(String value)
    {
        listViewId = value;
    }

    public PageReference ClearValues()
    {
        businessYears = null;
        cachedForecastYears = null;
        frameworkIds = null;
        System.debug(LoggingLevel.Error, '***JB*** Changing List View');
        System.debug(LoggingLevel.Error, '***JB*** listViewId: ' + listViewId);
        return null;
    }

    /*
    *   If the businessYears variable is empty, use PopulateRecords to get all of our
    *   variables setup
    */
    public List<String> GetBusinessYears()
    {
        if (businessYears == null)
        {
            businessYears = new List<String>();
            PopulateRecords();
        }
        return businessYears;
    }

    /*
    *   Sets the filter for the set controller (taken from the page) and gets the framework
    *   Ids corresponding to this list view
    */
    public Set<Id> GetFrameworkIds()
    {
        System.debug(LoggingLevel.Error, '***JB*** listViewId: ' + listViewId);
        if (frameworkIds == null)
        {
            GetFrameworkSetController().setFilterId(listViewId);
            frameworkIds = new Map<Id, Framework_Forecast__c>((List<Framework_Forecast__c>)frameworkSetController.getRecords()).keySet();
        }
        System.debug(LoggingLevel.Error, '***JB*** frameworkIds: ' + frameworkIds);
        return frameworkIds;
    }

    /*
    *   Initialises the required variables and queries the database for all records matching the framework
    *   Ids in the list view filter set. Loops through these, splitting by sector and then mapping a list
    *   of wrapped forecast frameworks by the relative business year. You'll end up with a list of wrapped
    *   forecasts for a framework for each business year. The wrapper sets the style class for each set of
    *   current/acknowledged values
    */
    public void PopulateRecords()
    {
        //Initialise framework forecast year maps
        wpsForecastYearByBY = new Map<String, List<ForecastYearStyleWrapper>>();
        cgForecastYearByBY = new Map<String, List<ForecastYearStyleWrapper>>();
        forecastYearMapInMemory = new Map<Id, Framework_Forecast_Year__c>();
        yearTotals = new Map<String,String>();
        yearTotalsDec = new Map<String,Decimal>();
        cgTotals = new Map<String,String>();
        cgTotalsDec = new Map<String,Decimal>();
        wpsTotals = new Map<String,String>();
        wpsTotalsDec = new Map<String,Decimal>();
        businessYears = new List<String>();
        overallTotalDec = 0.00;
        overallTotal = convertDecimalToCurrency(overallTotalDec);


        //Query and loop through framework forecast years, checking for the sector and mapping by business year
        for(Framework_Forecast_Year__c ffy : GetRecords(GetFrameworkIds()))
        {

            Decimal currYearTotal = 0.00;
            Decimal currCgSectorTotal = 0.00;
            Decimal currWpsSectorTotal = 0.00;
            //Save to memory map, for us in update later
            forecastYearMapInMemory.put(ffy.Id, ffy);

            //Initialise list for business year if not already there
            if (!wpsForecastYearByBY.containsKey(ffy.Actual_Forecast_Year__c))
            {
                businessYears.add(ffy.Actual_Forecast_Year__c);
                wpsForecastYearByBY.put(ffy.Actual_Forecast_Year__c, new List<ForecastYearStyleWrapper>());
                cgForecastYearByBY.put(ffy.Actual_Forecast_Year__c, new List<ForecastYearStyleWrapper>());
            }

            //Check the sector and assign to the correct map
            if (ffy.Sector__c == Label.FF_Sector_WPS)
            {
                List<ForecastYearStyleWrapper> listToUpdate = wpsForecastYearByBY.get(ffy.Actual_Forecast_Year__c);
                ForecastYearStyleWrapper fysw =  new ForecastYearStyleWrapper (ffy);
                currYearTotal+=fysw.currTotal;
                currWpsSectorTotal+=fysw.currTotal;
                listToUpdate.add(fysw);
                if (wpsTotalsDec.get(ffy.Actual_Forecast_Year__c) > 0.0) currWpsSectorTotal +=wpsTotalsDec.get(ffy.Actual_Forecast_Year__c);
                wpsTotalsDec.put(ffy.Actual_Forecast_Year__c, currWpsSectorTotal.setScale(2));
                wpsTotals.put(ffy.Actual_Forecast_Year__c, convertDecimalToCurrency(currWpsSectorTotal.setScale(2)));

            }
            else
            {
                List<ForecastYearStyleWrapper> listToUpdate = cgForecastYearByBY.get(ffy.Actual_Forecast_Year__c);
                ForecastYearStyleWrapper fysw =  new ForecastYearStyleWrapper (ffy);
                currCgSectorTotal+=fysw.currTotal;
                currYearTotal+=fysw.currTotal;
                listToUpdate.add(fysw);
                if (cgTotalsDec.get(ffy.Actual_Forecast_Year__c) > 0.0) currCgSectorTotal +=cgTotalsDec.get(ffy.Actual_Forecast_Year__c);
                cgTotalsDec.put(ffy.Actual_Forecast_Year__c, currCgSectorTotal.setScale(2));
                cgTotals.put(ffy.Actual_Forecast_Year__c, convertDecimalToCurrency(currCgSectorTotal.setScale(2)));

            }
            if (yearTotalsDec.get(ffy.Actual_Forecast_Year__c) > 0.0) currYearTotal +=yearTotalsDec.get(ffy.Actual_Forecast_Year__c);
            yearTotalsDec.put(ffy.Actual_Forecast_Year__c, currYearTotal.setScale(2));
            yearTotals.put(ffy.Actual_Forecast_Year__c, convertDecimalToCurrency(currYearTotal.setScale(2)));
            overallTotalDec += currYearTotal.setScale(2);
        }
        overallTotal = convertDecimalToCurrency(overallTotalDec);
    }

    /*
    *   Convert a decimal to a string in currency format (1000.00 becomes 1,000.00)
    */
    public String convertDecimalToCurrency(Decimal dec){
        String amount;
        if (!string.valueof(dec.format()).right(3).contains('.')){
            amount = string.valueof(dec.format()) + '.00';
        }else if (string.valueof(dec.format()).right(2).contains('.')){
            amount = string.valueof(dec.format()) + '0';
        }else {
            amount = string.valueof(dec.format());
        }

        return amount;
    }

    /*
    *   Cache the forecast year records, for re-use later
    */
    public List<Framework_Forecast_Year__c> GetRecords(Set<Id> frameworksToMatch)
    {
        if (cachedForecastYears == null)
        {
            cachedForecastYears = new List<Framework_Forecast_Year__c>(
                                                [SELECT Name, M01__c, M02__c, M03__c, M04__c, M05__c, M06__c, M07__c, M08__c, M09__c, M10__c, 
                                                        M11__c, M12__c, Q1__c, Q2__c, Q3__c, Q4__c, Annual__c, Last_Acknowledged_By__c, Last_Acknowledged_Date__c,
                                                        Forecast__c, Acknowledged_M01__c, Acknowledged_M02__c, Acknowledged_M03__c, Acknowledged_M04__c,
                                                        Acknowledged_M05__c, Acknowledged_M06__c, Acknowledged_M07__c, Acknowledged_M08__c, Acknowledged_M09__c,
                                                        Acknowledged_M10__c, Acknowledged_M11__c, Acknowledged_M12__c, Acknowledged_Q1__c, Acknowledged_Q2__c,
                                                        Acknowledged_Q3__c, Acknowledged_Q4__c, Acknowledged_Annual__c, Actual_Forecast_Year__c, Sector__c, Relative_Forecast_Year__c,
                                                        Forecast__r.Framework__r.Name
                                                FROM    Framework_Forecast_Year__c
                                                WHERE   Forecast__c IN :frameworksToMatch
                                                AND     RecordType.Name = 'Live'
                                                ORDER BY Actual_Forecast_Year__c ASC, Relative_Forecast_Year__c ASC, Forecast__c ASC]);
        }
        return cachedForecastYears;
    }

    /*
    *   Called from a button on the page to set the acknowledged values to the
    *   current values, save the record and reRender the page, printing any
    *   applicable errors
    */
    public PageReference AcknowledgeYear()
    {
        Framework_Forecast_Year__c ffyToUpdate = forecastYearMapInMemory.get(acknowledgedForecastYearId);

        //Acknowledge the record selected
        FrameworkForecastUtil.SetAcknowledgedValues(ffyToUpdate);
        Database.SaveResult sr = Database.update(ffyToUpdate);

        //If the save was unsuccessful, print the error. Otherwise, reset the wrapper for this record
        if (!sr.isSuccess())
        {
            String errorMessage = 'Unable to acknowledge year. Error message: ' + sr.getErrors().get(0).getMessage();
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, errorMessage));
        }
        PopulateRecords();

        return null;
    }
}