force-app/main/default/objects/Sprint__c/Sprint__c.object-meta.xml
<CustomObject>
    <description>CCS Agile Development Sprint Object</description>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sprint__c/fields/Sprint_Status__c.field-meta.xml
<CustomField>
    <fullName>Sprint_Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Committed</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sprint__c/fields/Sprint_Workstream__c.field-meta.xml
<CustomField>
    <fullName>Sprint_Workstream__c</fullName>
    <label>Workstream</label>
    <referenceTo>Workstream__c</referenceTo>
    <relationshipLabel>Sprints</relationshipLabel>
    <relationshipName>Sprints</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Story__c/User_Story__c.object-meta.xml
<CustomObject>
    <description>CCS Agile Development User Story Object</description>
    <label>User Story</label>
    <nameField>
        <displayFormat>US{0000}</displayFormat>
        <label>User Story</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Story__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>US_Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Awaiting Sizing</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>New Story</fullName>
            </value>
            <value>
                <fullName>Not Possible</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Refinement</fullName>
            </value>
            <value>
                <fullName>Quality Assurance</fullName>
            </value>
            <value>
                <fullName>User Acceptance Testing</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Ready for PreProd</fullName>
            </value>
            <value>
                <fullName>PreProd Quality Assurance</fullName>
            </value>
            <value>
                <fullName>Ready for Production</fullName>
            </value>
            <value>
                <fullName>Ready for QA</fullName>
            </value>
            <value>
                <fullName>Training Requirement</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Testing Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Story__c/fields/US_Business_Owner__c.field-meta.xml
<CustomField>
    <fullName>US_Business_Owner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Business Owner</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Story__c/fields/US_Category__c.field-meta.xml
<CustomField>
    <fullName>US_Category__c</fullName>
    <description>US560 - Sprint v2</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EPIC</fullName>
            </value>
            <value>
                <fullName>Hot Fix (D2P)</fullName>
            </value>
            <value>
                <fullName>Bug Fix</fullName>
            </value>
            <value>
                <fullName>Low Risk (D2P)</fullName>
            </value>
            <value>
                <fullName>Feature Request</fullName>
            </value>
            <value>
                <fullName>Tweak</fullName>
            </value>
            <value>
                <fullName>Investigation Spike</fullName>
            </value>
            <value>
                <fullName>System Maintenance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Story__c/fields/US_MOSCOW__c.field-meta.xml
<CustomField>
    <fullName>US_MOSCOW__c</fullName>
    <label>MOSCOW</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Must</fullName>
            </value>
            <value>
                <fullName>Should</fullName>
            </value>
            <value>
                <fullName>Could</fullName>
            </value>
            <value>
                <fullName>Wont</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Story__c/fields/US_Sprint__c.field-meta.xml
<CustomField>
    <fullName>US_Sprint__c</fullName>
    <label>Sprint</label>
    <referenceTo>Sprint__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Story__c/fields/US_Status__c.field-meta.xml
<CustomField>
    <fullName>US_Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In-Development</fullName>
            </value>
            <value>
                <fullName>In Testing</fullName>
            </value>
            <value>
                <fullName>Deployed</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
                <isActive>false</isActive>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Business Acceptace</fullName>
                <isActive>false</isActive>
                <label>Business Acceptace</label>
            </value>
            <value>
                <fullName>Business Review</fullName>
                <isActive>false</isActive>
                <label>Business Review</label>
            </value>
            <value>
                <fullName>Defined</fullName>
                <isActive>false</isActive>
                <label>Defined</label>
            </value>
            <value>
                <fullName>In-QA</fullName>
                <isActive>false</isActive>
                <label>In-QA</label>
            </value>
            <value>
                <fullName>New Story</fullName>
                <isActive>false</isActive>
                <label>New Story</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
            <value>
                <fullName>Three Amigos</fullName>
                <isActive>false</isActive>
                <label>Three Amigos</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Story__c/fields/US_Story_Detail__c.field-meta.xml
<CustomField>
    <fullName>US_Story_Detail__c</fullName>
    <label>Story Detail</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/User_Story__c/fields/US_Subject__c.field-meta.xml
<CustomField>
    <fullName>US_Subject__c</fullName>
    <label>Subject</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Story__c/fields/US_Tester__c.field-meta.xml
<CustomField>
    <fullName>US_Tester__c</fullName>
    <description>US0548 - Sprint v2</description>
    <label>Tester</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Workstream__c/Workstream__c.object-meta.xml
<CustomObject>
    <description>CCS Agile Development Workstream Object</description>
    <label>Workstream</label>
    <nameField>
        <label>Workstream Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workstreams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Workstream__c/fields/Delivery_Manager__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Workstreams1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Workstream__c/fields/Product_Manager__c.field-meta.xml
<CustomField>
    <fullName>Product_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Workstreams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UserStoryKanbanController_Test.cls
@isTest
public class UserStoryKanbanController_Test {
    
    @testSetup
    static void createGlobalTestData() {
        
    }
    
    @isTest 
    static void testController() {
        Workstream__c workstream;
        Sprint__c sprint;
        User_Story__c userStory;
        
        // Create an account for the product manager user. 
        User productManagerUser   = [SELECT Id FROM User WHERE Name != 'portal Site Guest User' AND isActive = true LIMIT 1]; 
        System.debug('Product Manager User' + ' '+ productManagerUser.Id);
        String prodAccountName  = 'Test Account ' + UnitTestDataFactory.getRandomString(8);
        Account prodAcc = UnitTestDataFactory.createSupplierAccount(prodAccountName);
        System.debug('ACCOUNT' + ' ' + prodAcc);
        prodAcc.OwnerId = productManagerUser.Id;
        insert prodAcc;
        
        // Create an account for the delivery manager user. 
        User deliveryManagerUser   = [SELECT Id FROM User WHERE Name != 'portal Site Guest User' AND isActive = true LIMIT 1]; 
        String deliverAccountName  = 'Test Account ' + UnitTestDataFactory.getRandomString(8);
        Account deliverAcc = UnitTestDataFactory.createSupplierAccount(deliverAccountName);
        deliverAcc.OwnerId = deliveryManagerUser.Id;
        insert deliverAcc;
        
        // Create Workstream
        workstream = new Workstream__c();
        workstream.Name ='TestWorkstream';
        workstream.Product_Manager__c = productManagerUser.Id;
        workstream.Delivery_Manager__c = deliveryManagerUser.Id;
        insert workstream;
        
        // Create Sprint
        sprint = new Sprint__c();
        sprint.Name = 'TestSprint';
        sprint.Sprint_Workstream__c = workstream.Id;
        sprint.Sprint_Status__c = 'Planning';
        insert sprint;
        
        // Create an account for the business owner user. 
        User accountOwnerUser   = [SELECT Id FROM User WHERE Name != 'portal Site Guest User' AND isActive = true LIMIT 1]; 
        String testAccountName  = 'Test Account ' + UnitTestDataFactory.getRandomString(8);
        Account testAcc = UnitTestDataFactory.createSupplierAccount(testAccountName);
        testAcc.OwnerId = accountOwnerUser.Id;
        insert testAcc;
       
        
        // Create the  contact
        Contact busOwnerContact = UnitTestDataFactory.createContact(testAcc.Id); 
        insert busOwnerContact;     
        
        
        // Create User Story
        userStory = new User_Story__c();
        userStory.US_Sprint__c = sprint.Id;
        userStory.US_MOSCOW__c = 'Must';
        userStory.US_Subject__c = 'TestSubject';
        userStory.US_Story_Detail__c = 'TestDetail';
        userStory.US_Status__c = 'In-Development';
        userStory.Stage__c = 'Working';
        userStory.US_Tester__c = 'John Denford';
        userStory.US_Category__c = 'Tweak';
        
        userStory.US_Business_Owner__c = busOwnerContact.Id;
        
        insert userStory;
        
        PageReference pageRef = Page.KanbanUserStory;
        Test.setCurrentPage(pageRef);
        test.startTest();
        
        ApexPages.currentPage().getParameters().put('sprintid', sprint.Id);
        UserStoryKanbanController controller;
        controller = new UserStoryKanbanController();
        
        List<User_Story__c> devStories;
        
        devStories = controller.allStories.get('In-Development');
        
        System.assertEquals(devStories[0].US_Subject__c,'TestSubject');
        
        UserStoryKanbanController.UpdateStatus result;
        result = UserStoryKanbanController.updateStoryStatus(devStories[0].Id,'Deployed');
        
        System.assert(result.isSuccess, 'Failed to move a user story');
        
        delete devStories[0];
        
        result = UserStoryKanbanController.updateStoryStatus(devStories[0].Id,'Deployed');
        System.assert(!result.isSuccess, 'User story should have been deleted');
        test.stopTest();
    }
    
}