force-app/main/default/objects/Sprint__c/Sprint__c.object-meta.xml
<CustomObject>
    <description>CCS Agile Development Sprint Object</description>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sprint__c/fields/Sprint_Days_to_Completion__c.field-meta.xml
<CustomField>
    <fullName>Sprint_Days_to_Completion__c</fullName>
    <formula>IF((Sprint_End_Date__c - Today()) &lt;= 0, 0, Sprint_End_Date__c - Today())</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days to Completion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sprint__c/fields/Sprint_Deployment_Date__c.field-meta.xml
<CustomField>
    <fullName>Sprint_Deployment_Date__c</fullName>
    <label>Deployment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sprint__c/fields/Sprint_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Sprint_End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sprint__c/fields/Sprint_Plan_Estimate__c.field-meta.xml
<CustomField>
    <fullName>Sprint_Plan_Estimate__c</fullName>
    <label>Plan Estimate</label>
    <summarizedField>User_Story__c.US_Plan_Estimate__c</summarizedField>
    <summaryForeignKey>User_Story__c.US_Sprint__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Sprint__c/fields/Sprint_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Sprint_Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sprint__c/fields/Sprint_Status__c.field-meta.xml
<CustomField>
    <fullName>Sprint_Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Committed</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sprint__c/fields/Sprint_Stories__c.field-meta.xml
<CustomField>
    <fullName>Sprint_Stories__c</fullName>
    <label>Sprint Stories</label>
    <summaryForeignKey>User_Story__c.US_Sprint__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Sprint__c/fields/Sprint_Workstream__c.field-meta.xml
<CustomField>
    <fullName>Sprint_Workstream__c</fullName>
    <label>Workstream</label>
    <referenceTo>Workstream__c</referenceTo>
    <relationshipLabel>Sprints</relationshipLabel>
    <relationshipName>Sprints</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Story__c/User_Story__c.object-meta.xml
<CustomObject>
    <description>CCS Agile Development User Story Object</description>
    <label>User Story</label>
    <nameField>
        <displayFormat>US{0000}</displayFormat>
        <label>User Story</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Story__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>US_Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Awaiting Sizing</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>New Story</fullName>
            </value>
            <value>
                <fullName>Not Possible</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Refinement</fullName>
            </value>
            <value>
                <fullName>Quality Assurance</fullName>
            </value>
            <value>
                <fullName>User Acceptance Testing</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Ready for PreProd</fullName>
            </value>
            <value>
                <fullName>PreProd Quality Assurance</fullName>
            </value>
            <value>
                <fullName>Ready for Production</fullName>
            </value>
            <value>
                <fullName>Ready for QA</fullName>
            </value>
            <value>
                <fullName>Training Requirement</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Testing Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Story__c/fields/US_Blocked__c.field-meta.xml
<CustomField>
    <fullName>US_Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Blocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User_Story__c/fields/US_Category__c.field-meta.xml
<CustomField>
    <fullName>US_Category__c</fullName>
    <description>US560 - Sprint v2</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EPIC</fullName>
            </value>
            <value>
                <fullName>Hot Fix (D2P)</fullName>
            </value>
            <value>
                <fullName>Bug Fix</fullName>
            </value>
            <value>
                <fullName>Low Risk (D2P)</fullName>
            </value>
            <value>
                <fullName>Feature Request</fullName>
            </value>
            <value>
                <fullName>Tweak</fullName>
            </value>
            <value>
                <fullName>Investigation Spike</fullName>
            </value>
            <value>
                <fullName>System Maintenance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Story__c/fields/US_Developer__c.field-meta.xml
<CustomField>
    <fullName>US_Developer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Developer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Stories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Story__c/fields/US_MOSCOW__c.field-meta.xml
<CustomField>
    <fullName>US_MOSCOW__c</fullName>
    <label>MOSCOW</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Must</fullName>
            </value>
            <value>
                <fullName>Should</fullName>
            </value>
            <value>
                <fullName>Could</fullName>
            </value>
            <value>
                <fullName>Wont</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Story__c/fields/US_Plan_Estimate__c.field-meta.xml
<CustomField>
    <fullName>US_Plan_Estimate__c</fullName>
    <label>Plan Estimate</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User_Story__c/fields/US_Sprint__c.field-meta.xml
<CustomField>
    <fullName>US_Sprint__c</fullName>
    <label>Sprint</label>
    <referenceTo>Sprint__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User_Story__c/fields/US_Status__c.field-meta.xml
<CustomField>
    <fullName>US_Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In-Development</fullName>
            </value>
            <value>
                <fullName>In Testing</fullName>
            </value>
            <value>
                <fullName>Deployed</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
                <isActive>false</isActive>
                <label>Accepted</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Business Acceptace</fullName>
                <isActive>false</isActive>
                <label>Business Acceptace</label>
            </value>
            <value>
                <fullName>Business Review</fullName>
                <isActive>false</isActive>
                <label>Business Review</label>
            </value>
            <value>
                <fullName>Defined</fullName>
                <isActive>false</isActive>
                <label>Defined</label>
            </value>
            <value>
                <fullName>In-QA</fullName>
                <isActive>false</isActive>
                <label>In-QA</label>
            </value>
            <value>
                <fullName>New Story</fullName>
                <isActive>false</isActive>
                <label>New Story</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
            <value>
                <fullName>Three Amigos</fullName>
                <isActive>false</isActive>
                <label>Three Amigos</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Story__c/fields/US_Subject__c.field-meta.xml
<CustomField>
    <fullName>US_Subject__c</fullName>
    <label>Subject</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Story__c/fields/US_Tester__c.field-meta.xml
<CustomField>
    <fullName>US_Tester__c</fullName>
    <description>US0548 - Sprint v2</description>
    <label>Tester</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Workstream__c/Workstream__c.object-meta.xml
<CustomObject>
    <description>CCS Agile Development Workstream Object</description>
    <label>Workstream</label>
    <nameField>
        <label>Workstream Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workstreams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/UserStoryKanbanController.cls
/*****************************************************************************************************************************
Name: UserStoryKanbanController

Purpose: Apex Controller for Visualforce Page (Kanban)

History
-------
VERSION AUTHOR                                   DATE            DETAIL  FEATURES/CSR/TTP
1.0 -   danny.evans@crowncommercial.gov.uk       28/09/2017      INITIAL DEVELOPMENT
2.0 -   danny.evans@crowncommercial.gov.uk       02/09/2018      Updated to include new features of Sprint 2.0
*******************************************************************************************************************************/


public class UserStoryKanbanController {
    public static String Story_MOVED = '{0} was moved successfully to {1}';
    
    public List<Schema.PicklistEntry> storyStatuses  { get; set; }
    public Map<String, List<User_Story__c>> allStories         { get; set; }
    private string sprintId;
    public Sprint__c sprint { get; set;}
    
    public class UpdateStatus {
        public Boolean isSuccess;
        public String message;
    }
    
    public UserStoryKanbanController() {
        sprintId = ApexPages.currentPage().getParameters().get('sprintid');
        storyStatuses = User_Story__c.US_Status__c.getDescribe().getPicklistValues();
        fetchSprint();
        fetchStories();
    }
    
    @RemoteAction
    public static UpdateStatus updateStoryStatus( Id storyId, String newStoryStatus ) {
        User_Story__c storyDetails;
        try{    
            storyDetails = [
                SELECT  Id
                ,Name
                FROM    User_Story__c
                WHERE   Id = :storyId
            ];
            
            
            storyDetails.US_Status__c = newStoryStatus;
            UPDATE storyDetails;
        }catch(Exception e){
            UpdateStatus failureDetails = new UpdateStatus();
            failureDetails.isSuccess    = false;
            failureDetails.message      = 'failed to move story : ' + e.getMessage();
            
            return failureDetails;
        }
        
        UpdateStatus updatedStoryDetails = new UpdateStatus();
        updatedStoryDetails.isSuccess    = true;
        updatedStoryDetails.message      = String.format( Story_MOVED, new List<String>{ storyDetails.Name, newStoryStatus } );
        
        return updatedStoryDetails;
    }
    
    private void fetchSprint(){
        sprint = [
            SELECT  Id
            ,Name
            ,Sprint_Days_to_Completion__c
            ,Sprint_Deployment_Date__c
            ,Sprint_End_Date__c
            ,Sprint_Plan_Estimate__c
            ,Sprint_Stories__c
            ,Sprint_Workstream__r.Name
            ,Sprint_Workstream__r.Id
            ,Sprint_Status__c
            ,Sprint_Start_Date__c
            FROM    Sprint__c
            Where Id = :sprintId
        ];
    }
    
    private void fetchStories() {
        List<User_Story__c> stories = [
            SELECT  Id
            ,Name
            ,US_Subject__c
            ,US_Status__c
            ,US_Plan_Estimate__c
            ,US_MOSCOW__c
            ,US_Developer__r.Name
            ,US_Blocked__c
            ,Stage__c
            ,US_Tester__c
            ,US_Category__c
            FROM    User_Story__c
            Where US_Sprint__c = :sprintId //AND US_Category__c != 'EPIC' // Code for v.2.1
        ];
        
        allStories = new Map<String, List<User_Story__c>>();
        
        for (Schema.PicklistEntry status : storyStatuses){
            allStories.put(status.getLabel(), new List<User_Story__c>());
        }
        
        for( User_Story__c story : stories ) {
            allStories.get( story.US_Status__c ).add( story );
        }
    }
}