force-app/main/default/objects/Ops_Workflow_Templates__c/Ops_Workflow_Templates__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting holding procurement templates and their mapping to stages and stage duration</description>
    <label>Ops Workflow Templates</label>
</CustomObject>

force-app/main/default/objects/Ops_Workflow_Templates__c/fields/End_SLA1__c.field-meta.xml
<CustomField>
    <fullName>End_SLA1__c</fullName>
    <defaultValue>false</defaultValue>
    <label>End SLA1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Ops_Workflow_Templates__c/fields/End_SLA2__c.field-meta.xml
<CustomField>
    <fullName>End_SLA2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>End SLA2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Ops_Workflow_Templates__c/fields/Record_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Name__c</fullName>
    <description>Keeps record type developer name for which this template applies to.</description>
    <label>Record Type Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ops_Workflow_Templates__c/fields/Seq__c.field-meta.xml
<CustomField>
    <fullName>Seq__c</fullName>
    <label>Seq#</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ops_Workflow_Templates__c/fields/Stage_Duration__c.field-meta.xml
<CustomField>
    <fullName>Stage_Duration__c</fullName>
    <label>Stage Duration</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ops_Workflow_Templates__c/fields/Stage_Id__c.field-meta.xml
<CustomField>
    <fullName>Stage_Id__c</fullName>
    <label>Stage Id</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ops_Workflow_Templates__c/fields/Start_SLA1__c.field-meta.xml
<CustomField>
    <fullName>Start_SLA1__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Start SLA1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Ops_Workflow_Templates__c/fields/Start_SLA2__c.field-meta.xml
<CustomField>
    <fullName>Start_SLA2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Start SLA2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Ops_Workflow_Templates__c/fields/Template_Name__c.field-meta.xml
<CustomField>
    <fullName>Template_Name__c</fullName>
    <label>Template Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Procurement_Stage__c/Procurement_Stage__c.object-meta.xml
<CustomObject>
    <label>Procurement Stage</label>
    <nameField>
        <label>Stage</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procurement Stages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Procurement_Stage__c/fields/Actual_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_End_Date__c</fullName>
    <inlineHelpText>Provides the actual end date for each stage based on progressing through the stages in the system. These are auto-populated dates</inlineHelpText>
    <label>Actual End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Procurement_Stage__c/fields/Actual_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Start_Date__c</fullName>
    <inlineHelpText>Provides the actual start date for each stage based on progressing through the stages in the system. These are auto-populated dates</inlineHelpText>
    <label>Actual Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Procurement_Stage__c/fields/Delivery_Duration__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Duration__c</fullName>
    <description>days needed to finish stage</description>
    <label>Delivery Duration</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Procurement_Stage__c/fields/End_SLA1__c.field-meta.xml
<CustomField>
    <fullName>End_SLA1__c</fullName>
    <defaultValue>false</defaultValue>
    <label>End SLA1?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Procurement_Stage__c/fields/End_SLA2__c.field-meta.xml
<CustomField>
    <fullName>End_SLA2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>End SLA2?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Procurement_Stage__c/fields/Seq__c.field-meta.xml
<CustomField>
    <fullName>Seq__c</fullName>
    <inlineHelpText>Provides the unique sequence for the specific stage within the procurement process</inlineHelpText>
    <label>Seq</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Procurement_Stage__c/fields/Stage_Id__c.field-meta.xml
<CustomField>
    <fullName>Stage_Id__c</fullName>
    <description>only for stages created from template</description>
    <label>Stage Id</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Procurement_Stage__c/fields/Start_SLA1__c.field-meta.xml
<CustomField>
    <fullName>Start_SLA1__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Start SLA1?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Procurement_Stage__c/fields/Start_SLA2__c.field-meta.xml
<CustomField>
    <fullName>Start_SLA2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Start SLA2?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ProcurementStageTriggerHelper.cls
/*********************************************************************
 Name:  ProcurementStageTriggerHelper()
 Copyright © 2016  Salesforce
 ======================================================
 ======================================================
 Purpose: handler class for procurement stage trigger                                                            
 -------                                                            
 ======================================================
 ======================================================
 History                                                            
 -------                                                            
 VERSION  AUTHOR            DATE             DETAIL				Description
   1.0   Klea Kolaric		2016-03-04		Initial version 	
   2.0	Cezary Zeleznicki	2016-11-02		Procurement RT change
 *********************************************************************/

public class ProcurementStageTriggerHelper {
	
	public static void onBeforeInsert(List<Procurement_Stage__c> triggerNew)
	{
		setStageDuration(triggerNew,null);
	}
	
	public static void onBeforeUpdate(List<Procurement_Stage__c> triggerNew, Map<Id,Procurement_Stage__c> oldMap)
	{
		setStageDuration(triggerNew,oldMap);
	}

	public static Map<String, Ops_Workflow_Templates__c> templatesWF(String recordTypeDeveloperName)
	{
		Map<String, Map<String, Ops_Workflow_Templates__c>> templatesWFByString = new Map<String, Map<String, Ops_Workflow_Templates__c>>();
		Map<String, Ops_Workflow_Templates__c> templatesWF = new Map<String, Ops_Workflow_Templates__c>();
		List<Ops_Workflow_Templates__c> wftemps = new List<Ops_Workflow_Templates__c>();

		if(Test.isRunningTest())
		{
			wftemps = [SELECT Name, End_SLA1__c, End_SLA2__c, Record_Type_Name__c, Seq__c, Stage_Duration__c, Stage_Id__c, Start_SLA1__c, Start_SLA2__c, Template_Name__c FROM Ops_Workflow_Templates__c];
		}
		else 
		{
			wftemps = Ops_Workflow_Templates__c.getAll().values();	
		}

		if(wftemps.size() != 0)
		{
			for(Ops_Workflow_Templates__c wftemp : wftemps)
			{
				if(!templatesWFByString.containsKey(wftemp.Record_Type_Name__c)) 
				{
					templatesWFByString.put(wftemp.Record_Type_Name__c, new Map<String, Ops_Workflow_Templates__c>());
					templatesWF.put(wftemp.Stage_Id__c, wftemp);
				}
				else
				{
					templatesWF.put(wftemp.Stage_Id__c, wftemp);
				}
			}
		}

		return templatesWF;
	}
	
	// US710 (calculate the actual time (in working days) that it took to deliver a stage)
	// this method will calculate the duration of a stage
	// we need to take into account business days and holidays so can only do this using BusinessHours.isWithin
	// this is why stage is calculated by icrementing start date day by day
	public static void setStageDuration(List<Procurement_Stage__c> stages, Map<Id,Procurement_Stage__c> oldMap)
	{
		for(Procurement_Stage__c st : stages)
		{
			// if both actual start and end date populated and record is new or has changed
			if(st.Actual_Start_Date__c != null && st.Actual_End_Date__c != null
				&& (oldMap == null || st.Actual_End_Date__c != oldMap.get(st.Id).Actual_End_Date__c))
			{
				st.Delivery_Duration__c = DateUtils.calculateDuration(st.Actual_Start_Date__c,st.Actual_End_Date__c);
			}
		}
	}
	
}