force-app/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <description>This object holds the Pillars, CCS Categories, CCS Subcategories, CAS Master Categories, CAS Categories, CAS Sub Categories and CAS Codes. They are hierarchical, and this is achieved via the [CategoryType] field, and the [Parent] self-lookup.</description>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Category__c/fields/CategoryType__c.field-meta.xml
<CustomField>
    <fullName>CategoryType__c</fullName>
    <description>This field specifies whether the record is a Pillar, Category or Subcategory</description>
    <inlineHelpText>This field specifies whether the record is a Pillar, Category or Subcategory</inlineHelpText>
    <label>Category Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pillar</fullName>
            </value>
            <value>
                <fullName>CCS Category</fullName>
            </value>
            <value>
                <fullName>CCS Sub Category</fullName>
            </value>
            <value>
                <fullName>CAS Master Category</fullName>
            </value>
            <value>
                <fullName>CAS Category</fullName>
            </value>
            <value>
                <fullName>CAS Sub Category</fullName>
            </value>
            <value>
                <fullName>Code</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Framework__c/Master_Framework__c.object-meta.xml
<CustomObject>
    <description>This object represents Framework related to Opportunity, Enquiry, and Category.</description>
    <label>Framework</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Frameworks</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Framework__c/fields/CCS_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>CCS_Sub_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is a lookup to the Category object.</description>
    <inlineHelpText>Identifies which CCS Sub Category the framework sits in (will affect all reporting in Data Warehouse)</inlineHelpText>
    <label>CCS Sub Category</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Category__c.CategoryType__c</field>
            <operation>equals</operation>
            <value>CCS Sub Category</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Frameworks</relationshipLabel>
    <relationshipName>Master_Framework</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Framework__c/fields/Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Date__c</fullName>
    <description>This is the date this Framework expires</description>
    <inlineHelpText>Date when agreement was originally going to end</inlineHelpText>
    <label>Original End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Master_Framework__c/fields/Long_Name__c.field-meta.xml
<CustomField>
    <fullName>Long_Name__c</fullName>
    <inlineHelpText>The Framework Name field holds 80 characters and the Framework Name (long) 255 characters. Both the Framework Name and Framework Name (long) fields must be populated.</inlineHelpText>
    <label>Name (long)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Framework__c/fields/RM_Number__c.field-meta.xml
<CustomField>
    <fullName>RM_Number__c</fullName>
    <description>A unique reference number from the Contract database</description>
    <inlineHelpText>Initial record created by BI through request from Strat Cat (google form)</inlineHelpText>
    <label>RM Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Framework__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Start date is the award date of your agreement (not the Go Live date)</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Master_Framework__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>* Live : Open contracts
* Expired : Closed and no more data to be received
* Expired - Data Still Received : Closed to new contracts but still receiving data
* Non CCS Managed : Not managed by CCS
* Cancelled: Cancelled</description>
    <inlineHelpText>* Live : Open contracts
* Expired : Closed and no more data to be received
* Expired - Data Still Received : Closed to new contracts but still receiving data
* Non CCS Managed : Not managed by CCS
* Cancelled: Cancelled</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Future (Pipeline)</fullName>
            </value>
            <value>
                <fullName>Planned (Pipeline)</fullName>
            </value>
            <value>
                <fullName>Underway (Pipeline)</fullName>
            </value>
            <value>
                <fullName>Awarded (Pipeline)</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Expired - Data Still Received</fullName>
            </value>
            <value>
                <fullName>Non CCS Managed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Framework_Lot__c/Master_Framework_Lot__c.object-meta.xml
<CustomObject>
    <description>Object to hold information regarding Framework Lots</description>
    <label>Framework Lot</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Framework Lots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Framework_Lot__c/fields/Award_Date__c.field-meta.xml
<CustomField>
    <fullName>Award_Date__c</fullName>
    <label>Award Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Master_Framework_Lot__c/fields/Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Date__c</fullName>
    <description>each lot on a framework may have a different date</description>
    <inlineHelpText>Lot end date. Shown on website</inlineHelpText>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Master_Framework_Lot__c/fields/Invoicing__c.field-meta.xml
<CustomField>
    <fullName>Invoicing__c</fullName>
    <label>Invoicing Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Framework_Lot__c/fields/Long_Name__c.field-meta.xml
<CustomField>
    <fullName>Long_Name__c</fullName>
    <inlineHelpText>This is the name of the lot, but the website displays the content of the &apos;Name&apos; field above.</inlineHelpText>
    <label>Name (long)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Framework_Lot__c/fields/Master_Framework__c.field-meta.xml
<CustomField>
    <fullName>Master_Framework__c</fullName>
    <description>Holds reference to Master Framework</description>
    <label>Framework</label>
    <referenceTo>Master_Framework__c</referenceTo>
    <relationshipLabel>Framework Lots</relationshipLabel>
    <relationshipName>Framework_Lots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Master_Framework_Lot__c/fields/Master_Framework_Lot_Number__c.field-meta.xml
<CustomField>
    <fullName>Master_Framework_Lot_Number__c</fullName>
    <description>Lot number field in SAFIRE</description>
    <inlineHelpText>Official number of the FW Lot.  Appears on the website</inlineHelpText>
    <label>Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Framework_Lot__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>* Live : Open contracts
* Expired : Closed and no more data to be received
* Expired - Data Still Received : Closed to new contracts but still receiving data</description>
    <inlineHelpText>* Live : Open contracts
* Expired : Closed and no more data to be received
* Expired - Data Still Received : Closed to new contracts but still receiving data</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Expired - Data Still Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Framework_Lot_Contact__c/Master_Framework_Lot_Contact__c.object-meta.xml
<CustomObject>
    <description>Holds association between Framework Lot and Contact</description>
    <label>Framework Lot Supplier Contact</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Ref#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Framework Lot Supplier Contacts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Framework_Lot_Contact__c/fields/Master_Framework_Lot__c.field-meta.xml
<CustomField>
    <fullName>Master_Framework_Lot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Framework Lot</label>
    <referenceTo>Master_Framework_Lot__c</referenceTo>
    <relationshipLabel>Framework Lot Supplier Contacts</relationshipLabel>
    <relationshipName>Framework_Lot_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Framework_Lot_Contact__c/fields/Supplier_Contact__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Appears on the website as the contact person for a given lot/supplier combination, but only if the website contact is ticked.</inlineHelpText>
    <label>Supplier Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Framework Lot Supplier Contacts</relationshipLabel>
    <relationshipName>Framework_Lot_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Framework_Lot__c/Supplier_Framework_Lot__c.object-meta.xml
<CustomObject>
    <label>Framework Lot Supplier</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Framework Lot Suppliers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Framework_Lot__c/fields/Master_Framework_Lot__c.field-meta.xml
<CustomField>
    <fullName>Master_Framework_Lot__c</fullName>
    <label>Framework Lot</label>
    <referenceTo>Master_Framework_Lot__c</referenceTo>
    <relationshipLabel>Framework Lot Suppliers</relationshipLabel>
    <relationshipName>Supplier_Framework_Lots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Supplier_Framework_Lot__c/fields/RM_Number__c.field-meta.xml
<CustomField>
    <fullName>RM_Number__c</fullName>
    <description>Framework RM Number</description>
    <formula>HYPERLINK(Master_Framework_Lot__r.Master_Framework__r.Id, Master_Framework_Lot__r.Master_Framework__r.RM_Number__c)</formula>
    <inlineHelpText>Framework RM Number</inlineHelpText>
    <label>RM Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Supplier_Framework_Lot__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>* Live : Open contracts
* Expired : Closed and no more data to be received
* Suspended : legally suspended due to a breach of contract</description>
    <inlineHelpText>* Live : Open contracts
* Expired : Closed and no more data to be received
* Suspended : legally suspended due to a breach of contract

Only suppliers with status of &apos;Live&apos; will be shown on the website.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Supplier_Framework_Lot__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Framework Lot Suppliers</relationshipLabel>
    <relationshipName>Supplier_Framework_Lots</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Supplier_Framework_Lot__c/fields/Supplier_Code__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Code__c</fullName>
    <description>code for Finance (CODA) system</description>
    <label>Supplier Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/bg_DeleteSupplierContactsControllerTest.cls
/** **************************************************************************************************************************
 * bg_DeleteSupplierContactsControllerTest.cls
 * @author Ibraaheem Fazal - BrightGen Ltd 
 * Date 13/10/17
 *****************************************************************************************************************************/

@isTest
private class bg_DeleteSupplierContactsControllerTest {

	 @testSetup static void setup() {

	 	Account acc1 = new Account();
	 	acc1.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Supplier').getRecordTypeId();
	 	acc1.name = 'test';
	 	insert acc1;

	 	Contact con1 = new Contact();
	 	con1.FirstName = 'Test';
	 	con1.LastName = 'Test';	
	 	con1.Accountid = acc1.id;
	 	con1.Email = 'Test@Test.com';
	 	insert con1;

	 	Category__c cat = new Category__c();
	 	cat.name = 'Test';
	 	cat.CategoryType__c = 'CCS Sub Category';
	 	insert cat;

	 	Master_Framework__c framework = new Master_Framework__c();
	 	framework.name = 'test';
	 	framework.Long_Name__c = 'test test';
	 	framework.CCS_Sub_Category__c = cat.id;
	 	framework.RM_Number__c = '00000000';
	 	framework.Status__c = 'live';
	 	framework.Start_Date__c = Date.Today();
	 	framework.Expiry_Date__c = Date.Today().addDays(100);
	 	insert framework;

	 	Master_Framework_Lot__c fl1 = new Master_Framework_Lot__c();
	 	fl1.name = 'test';
	 	fl1.Master_Framework__c = framework.id;
	 	fl1.Master_Framework_Lot_Number__c = '00000000';
	 	fl1.Invoicing__c = 'Monthly';
	 	fl1.Status__c = 'Live';
	 	fl1.Award_Date__c = Date.Today();
	 	fl1.Expiry_Date__c = Date.Today().addDays(100);
	 	insert fl1;

	 	Master_Framework_Lot__c fl2 = new Master_Framework_Lot__c();
	 	fl2.name = 'test';
	 	fl2.Master_Framework__c = framework.id;
	 	fl2.Master_Framework_Lot_Number__c = '00000000';
	 	fl2.Invoicing__c = 'Monthly';
	 	fl2.Status__c = 'Live';
	 	fl2.Award_Date__c = Date.Today();
	 	fl2.Expiry_Date__c = Date.Today().addDays(100);
	 	insert fl2;

	 	Supplier_Framework_Lot__c supplier = new Supplier_Framework_Lot__c();
	 	supplier.name = 'Test';
	 	supplier.Master_Framework_Lot__c = fl1.id;
	 	supplier.Supplier__c = acc1.id;
	 	supplier.Supplier_Code__c = 'test';
	 	insert supplier;

	 	Master_Framework_Lot_Contact__c flc1 = new Master_Framework_Lot_Contact__c();
	 	flc1.Master_Framework_Lot__c = fl1.id;
	 	flc1.Supplier_Contact__c = con1.id;
	 	insert flc1;

	 	Master_Framework_Lot_Contact__c flc2 = new Master_Framework_Lot_Contact__c();
	 	flc2.Master_Framework_Lot__c = fl2.id;
	 	flc2.Supplier_Contact__c = con1.id;
	 	insert flc2;

	 }
	
	@isTest static void removeContacts() {

		PageReference pageRef = Page.bg_DeleteFrameworkLotSupplierContacts;
        Test.setCurrentPage(pageRef);

        Master_Framework__c acc = [Select id from Master_Framework__c where name = 'test' limit 1];

        ApexPages.currentPage().getParameters().put('FrameworkID', acc.id);
      
        bg_DeleteSupplierContactsController controller = new bg_DeleteSupplierContactsController();
       
        controller.remove();

        for(ApexPages.Message msg :  ApexPages.getMessages()) {
        system.assertEquals('Please select a Supplier Contact', msg.getSummary());

    	}

    	Contact cont1 = [select id, name from Contact where FirstName = 'test'];

        controller.frameworkContact.Supplier_Contact__c = cont1.id;

        controller.find();

        controller.remove();

        controller.getdecision().set(0, true);

        controller.remove();

        system.assertEquals(controller.frameworkLotContactList.Size(), 1);



	}
	
	public static testMethod void findContacts () {

		PageReference pageRef = Page.bg_DeleteFrameworkLotSupplierContacts;
        Test.setCurrentPage(pageRef);

        Master_Framework__c acc = [Select id from Master_Framework__c where name = 'test' limit 1];

        ApexPages.currentPage().getParameters().put('FrameworkID', acc.id);
      
        bg_DeleteSupplierContactsController controller = new bg_DeleteSupplierContactsController();

        controller.find();

        List<ApexPages.Message> msgList = ApexPages.getMessages();

        for(ApexPages.Message msg :  ApexPages.getMessages()) {
        system.assertEquals('Please select a Supplier Contact', msg.getSummary());

    	}

        Contact cont1 = [select id, name from Contact where FirstName = 'test'];

        controller.frameworkContact.Supplier_Contact__c = cont1.id;

        controller.find();

        system.assertEquals(2, controller.frameworkLotContactList.Size());


		}
    
    @isTest
    public static void testGetters()
    {
        PageReference pageRef = Page.bg_DeleteFrameworkLotSupplierContacts;
        Test.setCurrentPage(pageRef);
        
        Master_Framework__c framework = [Select id from Master_Framework__c where name = 'test' limit 1];

        ApexPages.currentPage().getParameters().put('FrameworkID', framework.id);
      
        bg_DeleteSupplierContactsController controller = new bg_DeleteSupplierContactsController();
        
        System.assertEquals(framework.Id, controller.getFrameworkId());
        
        System.assertEquals(controller.searchRes, controller.getSearchResult());

        System.assertEquals(controller.frameworkLotContactList, controller.getframeworkLotContactList());

        System.assertEquals(controller.frameworkContact, controller.getframeworkContact());            
    }
	
}