force-app/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <description>This object holds the Pillars, CCS Categories, CCS Subcategories, CAS Master Categories, CAS Categories, CAS Sub Categories and CAS Codes. They are hierarchical, and this is achieved via the [CategoryType] field, and the [Parent] self-lookup.</description>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CCS_Contract__c/CCS_Contract__c.object-meta.xml
<CustomObject>
    <label>Contract</label>
    <nameField>
        <label>Contract Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CCS_Contract__c/fields/Contract_Finder_Notice_Id__c.field-meta.xml
<CustomField>
    <fullName>Contract_Finder_Notice_Id__c</fullName>
    <description>The unique ID for the contract notice which is auto-populated once ‘sent to’ Contracts Finder</description>
    <inlineHelpText>The unique ID for the contract notice which is auto-populated once ‘sent to’ Contracts Finder</inlineHelpText>
    <label>Contract Finder Notice Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCS_Contract__c/fields/Contract_Reference__c.field-meta.xml
<CustomField>
    <fullName>Contract_Reference__c</fullName>
    <inlineHelpText>The auto-generated unique 9 character reference for the procurement based on a pre-fix and the CAS category. This reference must be used on all procurement/contract documentation</inlineHelpText>
    <label>Contract Reference</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CCS_Contract__c/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <inlineHelpText>Provides the type of contract being advertised i.e Goods or Services or Goods and Services or Works</inlineHelpText>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Goods</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Goods &amp; Services</fullName>
            </value>
            <value>
                <fullName>Works</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCS_Contract__c/fields/Contract_Value__c.field-meta.xml
<CustomField>
    <fullName>Contract_Value__c</fullName>
    <inlineHelpText>Confirms the value of the contract</inlineHelpText>
    <label>Contract Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CCS_Contract__c/fields/Date_Contract_Awarded__c.field-meta.xml
<CustomField>
    <fullName>Date_Contract_Awarded__c</fullName>
    <inlineHelpText>This is the date the Contract was signed by the final party. Prior to 24/06/21 this was the date the outcome was issued.</inlineHelpText>
    <label>Contract Award Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CCS_Contract__c/fields/Deadline_Date__c.field-meta.xml
<CustomField>
    <fullName>Deadline_Date__c</fullName>
    <inlineHelpText>Provides the deadline for the procurement opportunity</inlineHelpText>
    <label>Closing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CCS_Contract__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Provides a succinct description for the contract</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CCS_Contract__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>Confirms the initial end date of the contract</inlineHelpText>
    <label>Original End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CCS_Contract__c/fields/Extension_Options__c.field-meta.xml
<CustomField>
    <fullName>Extension_Options__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>A ‘tick’ box to confirm if the contract has extension options. N.B A contract manager should ensure this matches the detail within the contract documents and associated Invitation to Tender</inlineHelpText>
    <label>Contract Extension Options</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CCS_Contract__c/fields/OJEU_Procedure_Type__c.field-meta.xml
<CustomField>
    <fullName>OJEU_Procedure_Type__c</fullName>
    <inlineHelpText>Provides the procurement type for which the contract was run under. A pre-defined list is available based on the Contracts Finder website options</inlineHelpText>
    <label>Procurement Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Other</fullName>
                <default>true</default>
                <label>Other</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Restricted</fullName>
            </value>
            <value>
                <fullName>Accelerated</fullName>
            </value>
            <value>
                <fullName>Negotiated</fullName>
            </value>
            <value>
                <fullName>AcceleratedNegotiated</fullName>
            </value>
            <value>
                <fullName>CompetitiveDialog</fullName>
            </value>
            <value>
                <fullName>NotApplicable</fullName>
            </value>
            <value>
                <fullName>NotSpecified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCS_Contract__c/fields/Regions__c.field-meta.xml
<CustomField>
    <fullName>Regions__c</fullName>
    <inlineHelpText>Provides details as to where the contract is for. The field already has the pre-defined list based on contracts finder</inlineHelpText>
    <label>Regions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>North East</fullName>
            </value>
            <value>
                <fullName>North West</fullName>
            </value>
            <value>
                <fullName>Yorkshire and The Humber</fullName>
            </value>
            <value>
                <fullName>East Midlands</fullName>
            </value>
            <value>
                <fullName>West Midlands</fullName>
            </value>
            <value>
                <fullName>East of England</fullName>
            </value>
            <value>
                <fullName>London</fullName>
            </value>
            <value>
                <fullName>South East</fullName>
            </value>
            <value>
                <fullName>South West</fullName>
            </value>
            <value>
                <fullName>Scotland</fullName>
            </value>
            <value>
                <fullName>Wales</fullName>
            </value>
            <value>
                <fullName>Northern Ireland</fullName>
            </value>
            <value>
                <fullName>Isle of Man</fullName>
            </value>
            <value>
                <fullName>Channel Islands</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCS_Contract__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>This is the date for which the contract formally starts and work commences</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract_Reference__c/Contract_Reference__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Lookup table to hold next number for a given master category code and year</description>
    <label>Contract Reference</label>
</CustomObject>

force-app/main/default/objects/Level_4_Categorisation_Code_for_Contract__c/Level_4_Categorisation_Code_for_Contract__c.object-meta.xml
<CustomObject>
    <label>Level 4 Categorisation Code for Contract</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Ref#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Level 4 Categorisation Code for Contract</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Level_4_Categorisation_Code_for_Contract__c/fields/CCS_Contract__c.field-meta.xml
<CustomField>
    <fullName>CCS_Contract__c</fullName>
    <label>CCS Contract</label>
    <referenceTo>CCS_Contract__c</referenceTo>
    <relationshipName>CAS_Sub_Category_Contract_Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/CFI_UpsertContract_CX_Test.cls
/*****************************************************************************************************************************
Name: CFI_UpsertContractService_Test

Purpose: Unit test for CFI_UpsertContract_CX

History
-------
VERSION AUTHOR                          DATE            DETAIL  FEATURES/CSR/TTP
1.0 -   pczechumski@salesforce.com      11/03/2016      INITIAL DEVELOPMENT
1.1 - 	Cezary Zeleznicki		04/01/2016	Increasing code coverege
*******************************************************************************************************************************/

@isTest (seeAllData=false)
private class CFI_UpsertContract_CX_Test{
	@isTest
	static void shouldFailOnLogin(){
		// given
		Boolean bUpsertSuccess;
		CFI_MockHttpResponseGenerator mock = new CFI_MockHttpResponseGenerator();
		mock.typeOfReponce = CFI_MockHttpResponseGenerator.FAIL_LOGIN_RESPONCE;
		Test.setMock(HttpCalloutMock.class, mock);

		UnitTestDataFactory tdf = new UnitTestDataFactory();
		tdf.initTestDataForContracts();

		Integer iNoMsg;

		// when
		Test.startTest();
			CFI_UpsertContract_CX ext = new CFI_UpsertContract_CX(new ApexPages.StandardController (tdf.liContracts[0]));
			iNoMsg = ApexPages.getMessages().size();
			System.assert(ext.disableUpsert,'Button should be disabled - required fields missing');
			ext.disableUpsert = false;
			ext.upsertContract();
		Test.stopTest();

		// then
		System.assertEquals(iNoMsg+1, ApexPages.getMessages().size(),'New error message had been added');
		ApexPages.message msg = ApexPages.getMessages()[iNoMsg];
		System.assertEquals(ApexPages.Severity.ERROR, msg.getSeverity(),'It should be error message on login fail');
		System.assert(!ext.disableUpsert,'Button should not be disabled after failed upsert');
		System.assert(ext.liFields != null && ext.liFields.size() > 0 ,'Query fields list is not empty');
		System.assert(ext.liContractRequiredFields != null && ext.liContractRequiredFields.size() > 0 ,
			'Required fields list is not empty');
		System.assert(ext.liSupplierRequiredFields != null && ext.liSupplierRequiredFields.size() > 0 ,
			'Required fields list is for supplier not empty');
	}

	@isTest
	static void shouldGetMessage(){
		// given
		CCS_Contract__c ccsContract = new CCS_Contract__c();
		CFI_UpsertContract_CX ext;
		ApexPages.message msg;
		Integer iNoMsg;

		// when - then
		// existing notice
		ccsContract.Contract_Finder_Notice_Id__c = 'aaaa-bbb-cccd-dddd';
		ext = new CFI_UpsertContract_CX(new ApexPages.StandardController (ccsContract));
		iNoMsg = ApexPages.getMessages().size();
		msg = ApexPages.getMessages()[iNoMsg-1];
		System.assertEquals(Label.CFI_StartMsgContractCreated,msg.getSummary(),
			'Should get notice already existing message');


		// no access message
		ccsContract.Contract_Finder_Notice_Id__c = null;
		ext = new CFI_UpsertContract_CX(new ApexPages.StandardController (ccsContract));
		ext.liMissedReqFields = new List<String> ();
		ext.displayWelcomeMessage();
		iNoMsg = ApexPages.getMessages().size();
		msg = ApexPages.getMessages()[iNoMsg-1];
		System.assertEquals(Label.CFI_Only_Edit_Access_Can_Send,msg.getSummary(),
			'Should get no edit access message');

		// start message
		ext.hasEditAccess = true;
		ext.displayWelcomeMessage();
		iNoMsg = ApexPages.getMessages().size();
		msg = ApexPages.getMessages()[iNoMsg-1];
		System.assertEquals(Label.CFI_StartMsg,msg.getSummary(),
			'Should get notice already existing message');
	}

	@isTest
	static void shouldUpsertContract(){
		CFI_UpsertContract_CX ext;
		ApexPages.message msg;
		Integer iNoMsg;

		UnitTestDataFactory tdf = new UnitTestDataFactory();
		tdf.initTestDataForContracts();

		Category__c cat = UnitTestDataFactory.createCategory();
		insert cat;

		CCS_Contract__c contract = tdf.liContracts[0];
		String strRef = UnitTestDataFactory.getRandomString(8);
		contract.Name = 'Contract-' + strRef;
		contract.Contract_Reference__c = strRef;
		contract.Start_Date__c = Date.today().addDays(24);
		contract.End_Date__c = Date.today().addYears(1);
		contract.Contract_Value__c = Integer.valueOf(Math.random() * 1000000);
		contract.Deadline_Date__c = Date.today().addYears(1);
		contract.Regions__c = 'test';
		contract.Description__c = 'Test';
		contract.Extension_Options__c = false;
		contract.Date_Contract_Awarded__c = Date.today().addDays(24);
		contract.OJEU_Procedure_Type__c = 'Test';
		contract.Contract_Type__c = 'Test contract';
		update contract;

		Level_4_Categorisation_Code_for_Contract__c code4 = UnitTestDataFactory.createCatContract(cat.Id, contract.Id);
		insert code4;

		CFI_MockHttpResponseGenerator mock = new CFI_MockHttpResponseGenerator();
		mock.typeOfReponce = CFI_MockHttpResponseGenerator.SUC_CREATE_NOTICE;
		Test.setMock(HttpCalloutMock.class, mock);

		Test.startTest();
		ext = new CFI_UpsertContract_CX(new ApexPages.StandardController(contract));
		ext.upsertContract();
		Test.stopTest();

		contract = [SELECT Id, Contract_Finder_Notice_Id__c FROM CCS_Contract__c WHERE Id = :contract.Id];
		iNoMsg = ApexPages.getMessages().size();
		msg = ApexPages.getMessages()[iNoMsg-1];

		System.assertNotEquals(null, contract.Contract_Finder_Notice_Id__c, 'Case should be updated with notice Id');
		System.assertEquals(ApexPages.Severity.INFO, msg.getSeverity(), 
			'Should get success msg');
	}

	@isTest
	static void shouldGenerateException(){
		CFI_UpsertContract_CX ext;
		ApexPages.message msg;
		ApexPages.message msg2;
		Integer iNoMsg;
		Boolean containsNoticeId;

		UnitTestDataFactory tdf = new UnitTestDataFactory();
		tdf.initTestDataForContracts();

		Category__c cat = UnitTestDataFactory.createCategory();
		insert cat;

		CCS_Contract__c contract = tdf.liContracts[0];
		String strRef = UnitTestDataFactory.getRandomString(8);
		contract.Name = 'Contract-' + strRef;
		contract.Contract_Reference__c = strRef;
		contract.Start_Date__c = Date.today().addDays(24);
		contract.End_Date__c = Date.today().addYears(1);
		contract.Contract_Value__c = Integer.valueOf(Math.random() * 1000000);
		contract.Deadline_Date__c = Date.today().addYears(1);
		contract.Regions__c = 'test';
		contract.Description__c = 'Test';
		contract.Extension_Options__c = false;
		contract.Date_Contract_Awarded__c = Date.today().addDays(24);
		contract.OJEU_Procedure_Type__c = 'Test';
		contract.Contract_Type__c = 'Test contract';
		update contract;

		Level_4_Categorisation_Code_for_Contract__c code4 = UnitTestDataFactory.createCatContract(cat.Id, contract.Id);
		insert code4;

		CFI_MockHttpResponseGenerator mock = new CFI_MockHttpResponseGenerator();
		mock.typeOfReponce = CFI_MockHttpResponseGenerator.SUC_GET_TOKEN;
		Test.setMock(HttpCalloutMock.class, mock);

		Test.startTest();
		ext = new CFI_UpsertContract_CX(new ApexPages.StandardController(contract));
		ext.upsertContract();
		contract = [SELECT Id, Contract_Finder_Notice_Id__c FROM CCS_Contract__c WHERE Id = :contract.Id];
		containsNoticeId = contract.Contract_Finder_Notice_Id__c != null;
		iNoMsg = ApexPages.getMessages().size();
		msg = ApexPages.getMessages()[iNoMsg-1];

		contract.Contract_Type__c = null;
		update contract;
		ext = new CFI_UpsertContract_CX(new ApexPages.StandardController(contract));
		ext.upsertContract();
		Test.stopTest();

		iNoMsg = ApexPages.getMessages().size();
		msg2 = ApexPages.getMessages()[iNoMsg-1];
		

		System.assert(!containsNoticeId, 'Case should not be updated with notice Id');
		System.assert(msg.getSummary().contains(Label.CFI_UnexpectedError.left(25)), 
			'Should generate Unexpected Error');
		System.assert(msg2.getSummary().contains(Label.CFI_ReqFieldMissing_AN), 
			'Should be missing fields');
	}

}