force-app/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <description>This object holds the Pillars, CCS Categories, CCS Subcategories, CAS Master Categories, CAS Categories, CAS Sub Categories and CAS Codes. They are hierarchical, and this is achieved via the [CategoryType] field, and the [Parent] self-lookup.</description>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Category__c/fields/Code_Type__c.field-meta.xml
<CustomField>
    <fullName>Code_Type__c</fullName>
    <label>Code Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CPV</fullName>
            </value>
            <value>
                <fullName>UNSPSC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCS_Contract__c/CCS_Contract__c.object-meta.xml
<CustomObject>
    <label>Contract</label>
    <nameField>
        <label>Contract Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CCS_Contract__c/fields/Procurement__c.field-meta.xml
<CustomField>
    <fullName>Procurement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Salesforce ID for the case that must not be used on any procurement/contract documentation</inlineHelpText>
    <label>Procurement</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>CCS_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Finder_Integration__c/Contract_Finder_Integration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Setting for Contract Finder Integarion</description>
    <label>Contract Finder Integration</label>
</CustomObject>

force-app/main/default/objects/Contract_Finder_Integration__c/fields/Credential__c.field-meta.xml
<CustomField>
    <fullName>Credential__c</fullName>
    <label>Credential</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Finder_Integration__c/fields/Test_Credentials__c.field-meta.xml
<CustomField>
    <fullName>Test_Credentials__c</fullName>
    <description>Holds username:password encoded, for sandboxes</description>
    <label>Test Credentials</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Finder_Integration__c/fields/Test_URL__c.field-meta.xml
<CustomField>
    <fullName>Test_URL__c</fullName>
    <description>Holds api url for sandboxes</description>
    <label>Test URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Finder_Integration__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <label>URL</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Level_4_Categorisation_Code_for_Contract__c/Level_4_Categorisation_Code_for_Contract__c.object-meta.xml
<CustomObject>
    <label>Level 4 Categorisation Code for Contract</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Ref#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Level 4 Categorisation Code for Contract</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Level_4_Categorisation_Code_for_Contract__c/fields/CCS_Contract__c.field-meta.xml
<CustomField>
    <fullName>CCS_Contract__c</fullName>
    <label>CCS Contract</label>
    <referenceTo>CCS_Contract__c</referenceTo>
    <relationshipName>CAS_Sub_Category_Contract_Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Level_4_Categorisation_Code_for_Contract__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <inlineHelpText>This provides the CPV code for the auto-link to Contracts Finder.</inlineHelpText>
    <label>Code</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Category__c.CategoryType__c</field>
            <operation>equals</operation>
            <value>Code</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Level 4 Categorisation Code for Contract</relationshipLabel>
    <relationshipName>CAS_Sub_Categories_for_Contract</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Procurement_Cat_Code__c/Procurement_Cat_Code__c.object-meta.xml
<CustomObject>
    <label>Level 4 Categorisation Code</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Level 4 Categorisation Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Level 4 Categorisation Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Procurement_Cat_Code__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <inlineHelpText>Provides the level 4 categorisation code. N.B The magnifier can be used to search for the relevant code using a keyword i.e Hardware</inlineHelpText>
    <label>Code</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Category__c.CategoryType__c</field>
            <operation>equals</operation>
            <value>Code</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Level 4 Categorisation Codes</relationshipLabel>
    <relationshipName>Procurement_Cat_Codes</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Procurement_Cat_Code__c/fields/Procurement__c.field-meta.xml
<CustomField>
    <fullName>Procurement__c</fullName>
    <inlineHelpText>Defaults with the case number and should not be amended</inlineHelpText>
    <label>Procurement</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Level 4 Categorisation Codes</relationshipLabel>
    <relationshipName>Procurement_Cat_Codes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CFI_UpsertContractService.cls
/*****************************************************************************************************************************
Name: CFI_UpsertContractService

Purpose: Service class for handling upsert operation for integration with Contact Finder

History
-------
VERSION AUTHOR                          DATE            DETAIL  FEATURES/CSR/TTP
1.0 -   pczechumski@salesforce.com      07/03/2016      INITIAL DEVELOPMENT
1.1	Cezary Zeleznicki		23/11/2016		Added new custom setting with credentails for sandboxes
1.2 	Cezary Zeleznicki		04/01/2016		Increasing code coverege
*******************************************************************************************************************************/

public without sharing class CFI_UpsertContractService {
/* without sharing since is service class for integration */

	public String baseURL; //API (callout) URL
	public String noticeId; // Contract finder notice id
	public String additionalDetailId; // Contract finder additional details id
	public List <String> liErros; // list of errors

	@TestVisible private String userPass; // encoded username:password
	@TestVisible private String securityToken;
	
	public CFI_UpsertContractService(){
		// intialize variables based on custom setting
		Boolean isSandbox = [SELECT Id, IsSandbox FROM Organization LIMIT 1].IsSandbox;
		Contract_Finder_Integration__c cfi = Contract_Finder_Integration__c.getInstance();
		this.baseURL = isSandbox ? cfi.Test_URL__c : cfi.URL__c;
		this.userPass = isSandbox ? cfi.Test_Credentials__c : cfi.Credential__c;
		liErros = new List <String> ();
	}

    /************************************************************
        Purpose: Method for checking if all required fields have been filled
        Parameters: -
        Returns: HttpResponse 
        Throws: -
    *************************************************************/    
    public static List <String> checkIfAllFieldsAreNotNull (SObject obj, List <String> liRequiredFields){
    	List <String> retVal = new List <String> ();

    	// get fields type
    	Map<String, Schema.SobjectField> fmap = obj.getSobjectType().getDescribe().fields.getMap();

    	for (String apiName : liRequiredFields){
    		Schema.SobjectField fld = fmap.get(apiName);

    		if (fld != null){
    			Schema.DescribeFieldResult dfr = fld.getDescribe();

    			if (dfr.getType() == Schema.DisplayType.String || dfr.getType() == Schema.DisplayType.EncryptedString 
    					|| dfr.getType() == Schema.DisplayType.TextArea){
    				if (String.isBlank((String)obj.get(apiName))){
    					retVal.add(dfr.getLabel());
    				}
    			}
    			else {
    				if (obj.get(apiName) == null){
    					retVal.add(dfr.getLabel());
    				}
    			}

    		}
    		else{
    			throw new CFI_Exception ('Field is not existing: ' + apiName);
    		}
    	}

    	return retVal;
    }

    /************************************************************
        Purpose: Method for getting cpv codes realted to given case
        Parameters: -
        Returns: -
        Throws: -
    *************************************************************/
    public static List<String> getCPVCodes(Case procurement){
    	List<String> retVal = new List<String>();

    	for (Procurement_Cat_Code__c pcc : [select Code__r.Name from Procurement_Cat_Code__c 
    			where Procurement__c = :procurement.id and Code__r.Code_Type__c = 'CPV']){
    		retVal.add(pcc.Code__r.Name);
    	}

    	return retVal;
    }


    /************************************************************
        Purpose: Check if user has edit right to record
        Parameters: user id, record id
        Returns:  true if user can edit record
        Throws: -
    *************************************************************/
    public static Boolean canEditRecord (id userId, Id recordId){
    	Boolean retVal = false;
    	List<UserRecordAccess> liUserAccess = [select HasEditAccess,RecordId 
    		from UserRecordAccess where UserId = :userId and RecordId = :recordId];

    	if (liUserAccess.size() > 0){
    		retVal = liUserAccess[0].HasEditAccess;
    	}

    	return retVal;
    }


    /************************************************************
        Purpose: Method for getting cpv codes realted to given contract
        Parameters: -
        Returns: -
        Throws: -
    *************************************************************/
    public static  List<String> getCPVCodes(CCS_Contract__c ccsContract){
    	List<String> retVal = new List<String>();

    	for (Level_4_Categorisation_Code_for_Contract__c code : 
    			[select Code__r.Name from Level_4_Categorisation_Code_for_Contract__c 
    			where CCS_Contract__c = :ccsContract.id and Code__r.Code_Type__c = 'CPV']){
    		retVal.add(code.Code__r.Name);
    	}

    	return retVal;
    }

    /************************************************************
        Purpose: Method for making callout
        Parameters: -
        Returns: HttpResponse 
        Throws: -
    *************************************************************/
	public HttpResponse makeCallout(String url, String requestType, String requestBody,
			Map <String, String> mHeaders){
		HttpResponse retVal;
		
		liErros = new List <String> ();
		Http h = new Http();
		HttpRequest req = new HttpRequest();
		req.setEndpoint(url);
		req.setMethod(requestType);
		req.setBody(requestBody);

		for (String key : mHeaders.keySet()){
			req.setHeader(key, mHeaders.get(key));
		}

		retVal = h.send(req);

		return retVal;
	}

	/************************************************************
        Purpose: Method for creating contract in Contract Finder
        Parameters: -
        Returns: -
        Throws: -
    *************************************************************/
    public Boolean upsertContract(CCS_Contract__c ccsContract, List <String> liCPVCodes){
    	// TODO validation before sending (check contact etc.)
    	Boolean bContinue = true;

    	// login
    	if (String.isBlank(securityToken)){
    		bContinue = Test.isRunningTest() ? true : logIn();
    	}

    	if (bContinue){
    		bContinue = insertDraftNotice(ccsContract, liCPVCodes);
    	}

    	if (bContinue){
    		bContinue = insertAward(ccsContract);
    	}

    	if (bContinue){
    		//bContinue = publishNotice(ccsContract); // do not publish as for US610
    	}

    	return bContinue;
    }

	/************************************************************
        Purpose: Method for creating contract in Contract Finder
        Parameters: -
        Returns: -
        Throws: -
    *************************************************************/
    public Boolean upsertOpporunityNotice(Case procurement, List <String> liCPVCodes){
    	// TODO validation before sending (check contact etc.)
    	Boolean bContinue = true;

    	// login
    	if (String.isBlank(securityToken)){
    		bContinue = Test.isRunningTest() ? true : logIn();
    	}

    	if (bContinue){
    		bContinue = insertDraftOpportunityNotice(procurement, liCPVCodes);
    	}

    	if (bContinue){
    		bContinue = insertAdditionalDetails(procurement.Additional_CF_Information__c);
    	}

    	return bContinue;
    }


    /************************************************************
        Purpose: Method for getting security token
        Parameters: -
        Returns: token string
        Throws: -
    *************************************************************/
	@TestVisible
	private Boolean logIn(){
		Boolean retVal = false;
		String requestBody = 'grant_type=client_credentials';
		Map <String, String> mHeaders = new Map <String, String>();
		mHeaders.put('Authorization', 'Basic ' + userPass);
		mHeaders.put('Content-Type', 'application/x-www-form-urlencoded');
		String url = baseURL + '/Token';

		HttpResponse res = makeCallout(url, 'POST', requestBody, mHeaders);
		
		if (res.getStatusCode() == 200){
			CFI_MessageFactory.TokenResp token = (CFI_MessageFactory.TokenResp)
			JSON.deserialize(res.getBody(), CFI_MessageFactory.TokenResp.class);
			securityToken = token.access_token;
			retVal = true;
		}
		else {
			String errorMsg = Label.CFI_LogginErrorMsg;
			liErros.add(errorMsg);
			ExceptionLoggingHelper.createErrorLog( UserInfo.getUserId(),'CFI_UpsertContractService','logIn' ,
                errorMsg, new CFI_Exception (errorMsg),'ERROR',null,null, 
                (Integer)DateTime.now().getTime(), 'CFI'
            );
		}

		return retVal;
	}

    /************************************************************
        Purpose: Method for creating new, draft notice
        Parameters: -
        Returns: notice id
        Throws: -
    *************************************************************/
	@TestVisible
	private Boolean insertDraftNotice(CCS_Contract__c ccsContract, List<String> liCPVCodes){
		Boolean retVal = false;
		String requestBody;
		Map <String, String> mHeaders = new Map <String, String>();
		mHeaders.put('Authorization', 'bearer ' + securityToken);
		mHeaders.put('Content-Type', 'application/json');
		String url = baseURL + '/Draft/Notice/Add?isPreAwarded=true';

		// get message body
		requestBody = CFI_MessageFactory.generateJSON(
			new CFI_MessageFactory.Notice(ccsContract, liCPVCodes));

		//ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, requestBody));

		HttpResponse res = makeCallout(url, 'POST', requestBody, mHeaders);

		if (res.getStatusCode() == 200){
			noticeId = res.getBody().replace('"','');
			retVal = true;
		}
		else {
			handleErrorResponce(res, 'insertDraftNotice');
		}

		return retVal;
	}

    /************************************************************
        Purpose: Method for adding new award to notice
        Parameters: -
        Returns: notice id
        Throws: -
    *************************************************************/
	@TestVisible
	private Boolean insertAward(CCS_Contract__c ccsContract){
		Boolean retVal = false;
		String requestBody;
		Map <String, String> mHeaders = new Map <String, String>();
		mHeaders.put('Authorization', 'bearer ' + securityToken);
		mHeaders.put('Content-Type', 'application/json');
		String url = baseURL + '/Draft/Award/Add';

		// get message body
		requestBody = CFI_MessageFactory.generateJSON(
			new CFI_MessageFactory.Award(ccsContract, noticeId));

		HttpResponse res = makeCallout(url, 'POST', requestBody, mHeaders);

		if (res.getStatusCode() == 200){
			retVal = true;
		}
		else {
			handleErrorResponce(res, 'insertAward');
		}

		return retVal;
	}

    /************************************************************
        Purpose: Method for publishing notice
        Parameters: -
        Returns: notice id
        Throws: -
    *************************************************************/
	@TestVisible
	private Boolean publishNotice(CCS_Contract__c ccsContract){
		Boolean retVal = false;
		String requestBody;
		Map <String, String> mHeaders = new Map <String, String>();
		mHeaders.put('Authorization', 'bearer ' + securityToken);
		mHeaders.put('Content-Type', 'application/json');
		String url = baseURL + '/Draft/Notice/Publish';

		// get message body
		requestBody = CFI_MessageFactory.generateJSON(
			new CFI_MessageFactory.Publish(noticeId, '', true));

		HttpResponse res = makeCallout(url, 'POST', requestBody, mHeaders);

		if (res.getStatusCode() == 200){
			retVal = true;
		}
		else {
			handleErrorResponce(res, 'publishNotice');
		}

		return retVal;
	}

	/************************************************************
        Purpose: Method for creating new, draft notice
        Parameters: -
        Returns: notice id
        Throws: -
    *************************************************************/
	@TestVisible
	private void handleErrorResponce (HttpResponse res, String methodName){
		String errorMsg;
		List <CFI_MessageFactory.ErrorMessage> liEM =  new List <CFI_MessageFactory.ErrorMessage>();
		if (res.getBody().startsWith('[')){
			liEM = (List <CFI_MessageFactory.ErrorMessage>)
				JSON.deserialize(res.getBody(), List<CFI_MessageFactory.ErrorMessage>.class);
		}
		else {
			// Single message
			liEm.add((CFI_MessageFactory.ErrorMessage) 
					JSON.deserialize(res.getBody(), CFI_MessageFactory.ErrorMessage.class));
		}

		for (CFI_MessageFactory.ErrorMessage em : liEM){
			errorMsg = String.format(Label.CFI_CalloutError, new List <String> {em.code, em.message, em.property});
			liErros.add(errorMsg);
			ExceptionLoggingHelper.createErrorLog( UserInfo.getUserId(),'CFI_UpsertContractService',methodName ,
                'Error on callout = ' + errorMsg, new CFI_Exception (errorMsg),'ERROR',null,null, 
                (Integer)DateTime.now().getTime(), 'CFI'
            );		
		}

	}


    /************************************************************
        Purpose: Method for creating new, draft notice
        Parameters: -
        Returns: notice id
        Throws: -
    *************************************************************/
	@TestVisible
	private Boolean insertDraftOpportunityNotice(Case procurement, List <String> liCPVCodes){
		Boolean retVal = false;
		String requestBody;
		Map <String, String> mHeaders = new Map <String, String>();
		mHeaders.put('Authorization', 'bearer ' + securityToken);
		mHeaders.put('Content-Type', 'application/json');
		String url = baseURL + '/Draft/Notice/Add?isPreAwarded=false';

		// get message body
		requestBody = CFI_MessageFactory.generateJSON(
			new CFI_MessageFactory.Notice(procurement, liCPVCodes));

		//ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, requestBody));
		HttpResponse res = makeCallout(url, 'POST', requestBody, mHeaders);

		if (res.getStatusCode() == 200){
			noticeId = res.getBody().replace('"','');
			retVal = true;
		}
		else {
			//ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, res.getBody()));
			handleErrorResponce(res, 'insertDraftOpportunityNotice');
		}

		return retVal;
	}

    /************************************************************
        Purpose: Send additional details (text) for existing notice
        Parameters: -
        Returns: true - if message was successfully send
        Throws: -
    *************************************************************/
	@TestVisible
	private Boolean insertAdditionalDetails(String text){
		Boolean retVal = false;
		String requestBody;
		Map <String, String> mHeaders = new Map <String, String>();
		mHeaders.put('Authorization', 'bearer ' + securityToken);
		mHeaders.put('Content-Type', 'application/json');
		String url = baseURL + '/Draft/AdditionalDetail/Add';

		// get message body
		requestBody = CFI_MessageFactory.generateJSON(
			new CFI_MessageFactory.AdditionalDetails(noticeId, text));

		HttpResponse res = makeCallout(url, 'POST', requestBody, mHeaders);

		if (res.getStatusCode() == 200){
			additionalDetailId = res.getBody().replace('"','');
			retVal = true;
		}
		else {
			handleErrorResponce(res, 'publishNotice');
		}

		return retVal;
	}



}