force-app/main/default/objects/Framework_Forecast_Year__c/Framework_Forecast_Year__c.object-meta.xml
<CustomObject>
    <description>Holds forecast information for relative future years for a given financial year</description>
    <label>Framework Forecast Year</label>
    <nameField>
        <displayFormat>FR{000000}</displayFormat>
        <label>Forecast Year #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Framework Forecast Years</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/Acknowledged_Annual__c.field-meta.xml
<CustomField>
    <fullName>Acknowledged_Annual__c</fullName>
    <label>Acknowledged Annual</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/Acknowledged_M01__c.field-meta.xml
<CustomField>
    <fullName>Acknowledged_M01__c</fullName>
    <label>Acknowledged M01</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/Acknowledged_M02__c.field-meta.xml
<CustomField>
    <fullName>Acknowledged_M02__c</fullName>
    <label>Acknowledged M02</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/Acknowledged_M03__c.field-meta.xml
<CustomField>
    <fullName>Acknowledged_M03__c</fullName>
    <label>Acknowledged M03</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/Acknowledged_M04__c.field-meta.xml
<CustomField>
    <fullName>Acknowledged_M04__c</fullName>
    <label>Acknowledged M04</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/Acknowledged_M05__c.field-meta.xml
<CustomField>
    <fullName>Acknowledged_M05__c</fullName>
    <label>Acknowledged M05</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/Acknowledged_Q4__c.field-meta.xml
<CustomField>
    <fullName>Acknowledged_Q4__c</fullName>
    <label>Acknowledged Q4</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/Annual__c.field-meta.xml
<CustomField>
    <fullName>Annual__c</fullName>
    <label>Annual</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/M01__c.field-meta.xml
<CustomField>
    <fullName>M01__c</fullName>
    <label>M01</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/M02__c.field-meta.xml
<CustomField>
    <fullName>M02__c</fullName>
    <label>M02</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/M03__c.field-meta.xml
<CustomField>
    <fullName>M03__c</fullName>
    <label>M03</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/M04__c.field-meta.xml
<CustomField>
    <fullName>M04__c</fullName>
    <label>M04</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/M05__c.field-meta.xml
<CustomField>
    <fullName>M05__c</fullName>
    <label>M05</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Framework_Forecast_Year__c/fields/Q4__c.field-meta.xml
<CustomField>
    <fullName>Q4__c</fullName>
    <label>Q4</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/bg_ForecastYearStyleWrapper_Test.cls
/******************************************************
 *  bg_ForecastYearStyleWrapper_Test
 *
 *  Test class for ForecastYearStyleWrapper class
 *
 *  Author: James Burgess - BrightGen Ltd
 *  Date:   20/09/2017
 *  Changes:
 *
 ******************************************************/
@isTest
private class bg_ForecastYearStyleWrapper_Test {

    private static testMethod void TestConstructor()
    {
        Framework_Forecast_Year__c testFfy = new Framework_Forecast_Year__c();
        testFfy.M01__c = 100;
		testFfy.M02__c = 200;
		testFfy.M03__c = 300;
		testFfy.M04__c = 400;
		testFfy.M05__c = 500;
		testFfy.Q4__c = 600;
		testFfy.Annual__c = 1200;
        testFfy.Acknowledged_M01__c = 200;//Lower
		testFfy.Acknowledged_M02__c = 100;//Higher
		testFfy.Acknowledged_M03__c = 100;//Higher
		testFfy.Acknowledged_M04__c = 600;//Lower
		testFfy.Acknowledged_M05__c = 500;
		testFfy.Acknowledged_Q4__c = 600;
		testFfy.Acknowledged_Annual__c = 2000;//Lower

        ForecastYearStyleWrapper testResult = new ForecastYearStyleWrapper(testFfy);

        System.assertEquals('lower', testResult.classByField.get('M01__c'));
        System.assertEquals('lower', testResult.classByField.get('Acknowledged_M01__c'));
        System.assertEquals('higher', testResult.classByField.get('M02__c'));
        System.assertEquals('higher', testResult.classByField.get('Acknowledged_M02__c'));
        System.assertEquals('higher', testResult.classByField.get('M03__c'));
        System.assertEquals('higher', testResult.classByField.get('Acknowledged_M03__c'));
        System.assertEquals('lower', testResult.classByField.get('M04__c'));
        System.assertEquals('lower', testResult.classByField.get('Acknowledged_M04__c'));
        System.assertEquals('', testResult.classByField.get('M05__c'));
        System.assertEquals('', testResult.classByField.get('Acknowledged_M05__c'));
        System.assertEquals('', testResult.classByField.get('Q4__c'));
        System.assertEquals('', testResult.classByField.get('Acknowledged_Q4__c'));
        System.assertEquals('lower', testResult.classByField.get('Annual__c'));
        System.assertEquals('lower', testResult.classByField.get('Acknowledged_Annual__c'));
    }
}