force-app/main/default/objects/CCS_Contract__c/CCS_Contract__c.object-meta.xml
<CustomObject>
    <label>Contract</label>
    <nameField>
        <label>Contract Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CCS_Contract__c/fields/Contract_Finder_Notice_Id__c.field-meta.xml
<CustomField>
    <fullName>Contract_Finder_Notice_Id__c</fullName>
    <description>The unique ID for the contract notice which is auto-populated once ‘sent to’ Contracts Finder</description>
    <inlineHelpText>The unique ID for the contract notice which is auto-populated once ‘sent to’ Contracts Finder</inlineHelpText>
    <label>Contract Finder Notice Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCS_Contract__c/fields/Contract_Reference__c.field-meta.xml
<CustomField>
    <fullName>Contract_Reference__c</fullName>
    <inlineHelpText>The auto-generated unique 9 character reference for the procurement based on a pre-fix and the CAS category. This reference must be used on all procurement/contract documentation</inlineHelpText>
    <label>Contract Reference</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CCS_Contract__c/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <inlineHelpText>Provides the type of contract being advertised i.e Goods or Services or Goods and Services or Works</inlineHelpText>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Goods</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Goods &amp; Services</fullName>
            </value>
            <value>
                <fullName>Works</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCS_Contract__c/fields/Contract_Value__c.field-meta.xml
<CustomField>
    <fullName>Contract_Value__c</fullName>
    <inlineHelpText>Confirms the value of the contract</inlineHelpText>
    <label>Contract Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CCS_Contract__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Confirms who the customer organisation of the contract is</inlineHelpText>
    <label>Customer Organisation Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Organisation</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts (Customer)</relationshipLabel>
    <relationshipName>CCS_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCS_Contract__c/fields/Date_Contract_Awarded__c.field-meta.xml
<CustomField>
    <fullName>Date_Contract_Awarded__c</fullName>
    <inlineHelpText>This is the date the Contract was signed by the final party. Prior to 24/06/21 this was the date the outcome was issued.</inlineHelpText>
    <label>Contract Award Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CCS_Contract__c/fields/Deadline_Date__c.field-meta.xml
<CustomField>
    <fullName>Deadline_Date__c</fullName>
    <inlineHelpText>Provides the deadline for the procurement opportunity</inlineHelpText>
    <label>Closing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CCS_Contract__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Provides a succinct description for the contract</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CCS_Contract__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>Confirms the initial end date of the contract</inlineHelpText>
    <label>Original End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CCS_Contract__c/fields/Extension_Options__c.field-meta.xml
<CustomField>
    <fullName>Extension_Options__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>A ‘tick’ box to confirm if the contract has extension options. N.B A contract manager should ensure this matches the detail within the contract documents and associated Invitation to Tender</inlineHelpText>
    <label>Contract Extension Options</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CCS_Contract__c/fields/Is_Suitable_For_SME__c.field-meta.xml
<CustomField>
    <fullName>Is_Suitable_For_SME__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Required for Contract Finder</description>
    <inlineHelpText>A tick box to confirm if the requirement is suitable for Small and Medium Sized enterprises</inlineHelpText>
    <label>Is Suitable For SME</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CCS_Contract__c/fields/Is_Suitable_for_VCSE__c.field-meta.xml
<CustomField>
    <fullName>Is_Suitable_for_VCSE__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Required for Contract Finder</description>
    <inlineHelpText>A tick box to confirm if the requirement is suitable for Voluntary, Community and Social Enterprises</inlineHelpText>
    <label>Is Suitable for VCSE</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CCS_Contract__c/fields/OJEU_Procedure_Type__c.field-meta.xml
<CustomField>
    <fullName>OJEU_Procedure_Type__c</fullName>
    <inlineHelpText>Provides the procurement type for which the contract was run under. A pre-defined list is available based on the Contracts Finder website options</inlineHelpText>
    <label>Procurement Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Other</fullName>
                <default>true</default>
                <label>Other</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Restricted</fullName>
            </value>
            <value>
                <fullName>Accelerated</fullName>
            </value>
            <value>
                <fullName>Negotiated</fullName>
            </value>
            <value>
                <fullName>AcceleratedNegotiated</fullName>
            </value>
            <value>
                <fullName>CompetitiveDialog</fullName>
            </value>
            <value>
                <fullName>NotApplicable</fullName>
            </value>
            <value>
                <fullName>NotSpecified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCS_Contract__c/fields/Parent_Group__c.field-meta.xml
<CustomField>
    <fullName>Parent_Group__c</fullName>
    <description>US451</description>
    <formula>Customer__r.Parent_Group__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This shows the organisation&apos;s ultimate parent or - if it has no parent - it shows the organisation itself</inlineHelpText>
    <label>Parent Group</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCS_Contract__c/fields/Regions__c.field-meta.xml
<CustomField>
    <fullName>Regions__c</fullName>
    <inlineHelpText>Provides details as to where the contract is for. The field already has the pre-defined list based on contracts finder</inlineHelpText>
    <label>Regions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>North East</fullName>
            </value>
            <value>
                <fullName>North West</fullName>
            </value>
            <value>
                <fullName>Yorkshire and The Humber</fullName>
            </value>
            <value>
                <fullName>East Midlands</fullName>
            </value>
            <value>
                <fullName>West Midlands</fullName>
            </value>
            <value>
                <fullName>East of England</fullName>
            </value>
            <value>
                <fullName>London</fullName>
            </value>
            <value>
                <fullName>South East</fullName>
            </value>
            <value>
                <fullName>South West</fullName>
            </value>
            <value>
                <fullName>Scotland</fullName>
            </value>
            <value>
                <fullName>Wales</fullName>
            </value>
            <value>
                <fullName>Northern Ireland</fullName>
            </value>
            <value>
                <fullName>Isle of Man</fullName>
            </value>
            <value>
                <fullName>Channel Islands</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CCS_Contract__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>This is the date for which the contract formally starts and work commences</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CCS_Contract__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Confirms who is the supplier for the contract</inlineHelpText>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts (Supplier)</relationshipLabel>
    <relationshipName>CCS_Contracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCS_Contract__c/fields/Supplier_Contact__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Confirms who the supplier contact is for the contract</inlineHelpText>
    <label>Supplier Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Supplier__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contracts (Supplier Contact)</relationshipLabel>
    <relationshipName>CCS_Contracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCS_Contract__c/fields/Synchronised_With_Contract_Finder__c.field-meta.xml
<CustomField>
    <fullName>Synchronised_With_Contract_Finder__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>A tick box to confirm if the contract notice has been ‘sent to’ Contracts Finder. (Auto-populated)</inlineHelpText>
    <label>Synchronised With Contract Finder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract_Reference__c/Contract_Reference__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Lookup table to hold next number for a given master category code and year</description>
    <label>Contract Reference</label>
</CustomObject>

force-app/main/default/classes/CFI_UpsertContract_CX.cls
/*****************************************************************************************************************************
Name: CFI_UpsertContractService_Test

Purpose: Controller extension for upserting contract in Contract Finder

History
-------
VERSION AUTHOR                                DATE            DETAIL  FEATURES/CSR/TTP
1.0 -   pczechumski@salesforce.com            12/03/2016      INITIAL DEVELOPMENT
1.1 -   danny.evans@crowncommercial.gov.uk    03/09/2018      Added On behalf of Customer and Parent Group
*******************************************************************************************************************************/

public with sharing class CFI_UpsertContract_CX {

    private final CCS_Contract__c ccsContract;
    public List <String> liFields = new LIST<String> {'Contract_Reference__c', 'name',
                'Customer__r.name', 'Start_Date__c', 'End_Date__c', 'Contract_Value__c',
                'Contract_Finder_Notice_Id__c', 'Synchronised_With_Contract_Finder__c',
                'Supplier__r.name', 'Supplier__r.DUNS_Number__c',
                'Supplier__r.BillingStreet', 'Supplier__r.BillingPostalCode', 
                'Supplier__r.BillingCity', 'Supplier__r.BillingCountry', 
                'Supplier__r.SME_Status__c','Supplier__r.Voluntary_Sector_Organisation__c',
                'Supplier_Contact__r.name',
                'Deadline_Date__c', 'Is_Suitable_For_SME__c', 'Is_Suitable_for_VCSE__c',
                'Regions__c', 'Description__c', 'Extension_Options__c', 'Date_Contract_Awarded__c',
                'OJEU_Procedure_Type__c', 'Contract_Type__c', 'Customer__r.Parent_Group__c' //Added for US537
            };

    public List <String> liContractRequiredFields = new LIST<String> {'Contract_Reference__c', 'name',
                'Start_Date__c', 'End_Date__c', 'Contract_Value__c', 'Deadline_Date__c', 'Regions__c', 
                'Description__c','Date_Contract_Awarded__c', 'OJEU_Procedure_Type__c', 'Contract_Type__c',
                'Customer__c', 'Supplier__c', 'Supplier_Contact__c'
            };

    public List <String> liSupplierRequiredFields = new LIST<String> {
                'name', 'DUNS_Number__c','BillingStreet', 'BillingPostalCode', 'BillingCity', 'BillingCountry'
            };

    
    public CFI_UpsertContract_CX(ApexPages.StandardController stdController) {
        if (!Test.isRunningTest()){
            stdController.addFields(liFields);
        }
        this.ccsContract = (CCS_Contract__c)stdController.getRecord();
        displayWelcomeMessage();
    }

    public Boolean hasEditAccess{
        get {
            if (hasEditAccess == null){
                hasEditAccess = CFI_UpsertContractService.canEditRecord(UserInfo.getUserId(),
                    this.ccsContract.Id);
            }
            return hasEditAccess;
        }
        set;
    }

    
    public Boolean disableUpsert{
        get {
            if (disableUpsert == null){
                disableUpsert = String.isNotBlank(ccsContract.Contract_Finder_Notice_Id__c)
                    || liMissedReqFields.size() > 0 || !hasEditAccess;
            }
            return disableUpsert;
        }
        set;
    }

    public List <String> liMissedReqFields{
        get {
            if (liMissedReqFields == null){
                liMissedReqFields = new List <String>();

                // check contract fields
                for (String strMissedFld : CFI_UpsertContractService.checkIfAllFieldsAreNotNull(ccsContract, 
                        liContractRequiredFields)){
                    liMissedReqFields.add('<li>Contract - ' + strMissedFld + '</li>');
                }

                // check supplier (account) fields
                if (ccsContract.Supplier__c != null){
                    for (String strMissedFld : CFI_UpsertContractService.checkIfAllFieldsAreNotNull(ccsContract.Supplier__r, 
                            liSupplierRequiredFields)){
                        liMissedReqFields.add('<li>Supplier - ' + strMissedFld + '</li>');
                    }
                }

                if (liCPVCodes.size() == 0){
                    liMissedReqFields.add('<li>CPV Codes</li>');
                }
            }

            return liMissedReqFields;
        }
        set;
    }    

    List <String> liCPVCodes{
        get {
            if (liCPVCodes == null){
                liCPVCodes = CFI_UpsertContractService.getCPVCodes(ccsContract);
            }

            return liCPVCodes;
        }
        set;
    }


    /************************************************************
        Purpose: Method for sending Contract to Contract Finder
        Parameters: -
        Returns: -
        Throws: -
    *************************************************************/

    public PageReference upsertContract(){
        try{
            if(disableUpsert){
                displayWelcomeMessage();
            }
            else{
                CFI_UpsertContractService ucs = new CFI_UpsertContractService();
                Boolean bSync = ucs.upsertContract(ccsContract, liCPVCodes);

                if (ucs.liErros != null && ucs.liErros.size() > 0){
                    handleErrors(ucs);
                }
                if(String.isNotBlank(ucs.noticeId)){
                    ccsContract.Contract_Finder_Notice_Id__c = ucs.noticeId;
                    ccsContract.Synchronised_With_Contract_Finder__c = bSync;

                    update ccsContract;
                    if (bSync){
                        displayMessage(ApexPages.Severity.INFO, Label.CFI_SuccessMessage + ucs.noticeId);
                    }

                    disableUpsert = true;
                }
            }

        }
        catch (Exception ex){
            displayMessage(ApexPages.Severity.ERROR, 
                String.format(Label.CFI_UnexpectedError, new List <String> {ex.getMessage()}));
        }
        return null;
    }

    /************************************************************
         Purpose: Helper method for dispalying apex messages
        Parameters: -
        Returns: -
        Throws: -
    *************************************************************/

    public void displayMessage(ApexPages.Severity lvl, String msg){
        ApexPages.addMessage(new ApexPages.Message(lvl, msg));
    }

    /************************************************************
        Purpose: Helper method for error handling
        Parameters: -
        Returns: -
        Throws: -
    *************************************************************/

    private void handleErrors(CFI_UpsertContractService ucs){
        for (String errMsg : ucs.liErros){
            displayMessage(ApexPages.Severity.ERROR, errMsg);
        }
    } 

    /************************************************************
        Purpose: Method for displaying welcome message to the user based on record state
        Parameters: -
        Returns: -
        Throws: -
    *************************************************************/
    @TestVisible
    private void displayWelcomeMessage(){
        if (String.isNotBlank(ccsContract.Contract_Finder_Notice_Id__c)){
            displayMessage(ApexPages.Severity.INFO, Label.CFI_StartMsgContractCreated);
        }
        else if (!hasEditAccess){
            displayMessage(ApexPages.Severity.INFO, Label.CFI_Only_Edit_Access_Can_Send);
        }
        else if(liMissedReqFields.size() > 0){
            displayMessage(ApexPages.Severity.WARNING, Label.CFI_ReqFieldMissing_AN + ' ' + String.join(liMissedReqFields, ' '));
        }
        else{
            displayMessage(ApexPages.Severity.INFO, Label.CFI_StartMsg);
        }
    }  
}