force-app/main/default/objects/Master_Framework_Lot__c/Master_Framework_Lot__c.object-meta.xml
<CustomObject>
    <description>Object to hold information regarding Framework Lots</description>
    <label>Framework Lot</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Framework Lots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Framework_Lot__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>* Live : Open contracts
* Expired : Closed and no more data to be received
* Expired - Data Still Received : Closed to new contracts but still receiving data</description>
    <inlineHelpText>* Live : Open contracts
* Expired : Closed and no more data to be received
* Expired - Data Still Received : Closed to new contracts but still receiving data</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Expired - Data Still Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Supplier_Framework_Lot__c/Supplier_Framework_Lot__c.object-meta.xml
<CustomObject>
    <label>Framework Lot Supplier</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Framework Lot Suppliers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Framework_Lot__c/fields/Master_Framework_Lot__c.field-meta.xml
<CustomField>
    <fullName>Master_Framework_Lot__c</fullName>
    <label>Framework Lot</label>
    <referenceTo>Master_Framework_Lot__c</referenceTo>
    <relationshipLabel>Framework Lot Suppliers</relationshipLabel>
    <relationshipName>Supplier_Framework_Lots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Supplier_Framework_Lot__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>* Live : Open contracts
* Expired : Closed and no more data to be received
* Suspended : legally suspended due to a breach of contract</description>
    <inlineHelpText>* Live : Open contracts
* Expired : Closed and no more data to be received
* Suspended : legally suspended due to a breach of contract

Only suppliers with status of &apos;Live&apos; will be shown on the website.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MasterFrameworkLotTriggerHandler.cls
/*********************************************************************
 Name:  MasterFrameworkLotTriggerHandler
 Copyright © 2016  Salesforce
 ======================================================
 ======================================================
 Purpose: handler class for Master Framework lots trigger                                                            
 -------                                                            
 ======================================================
 ======================================================
 History                                                            
 -------                                                            
 VERSION  AUTHOR            DATE             DETAIL             Description
   1.0   Piotr Czechumski   2016-04-20     	Initial version 
 *********************************************************************/
public class MasterFrameworkLotTriggerHandler {
	public static final String MFL_STATUS_EXPIRED = 'Expired';
	public static final String SFL_STATUS_EXPIRED = 'Expired';

	public static void onAfterUpdate(Map<Id,Master_Framework_Lot__c> oldMap, Map<Id,Master_Framework_Lot__c> newMap){
		checkAndUpdateSupplierFrameworkLotWhenExpired(oldMap, newMap);
	}

	/************************************************************
        Purpose: Method  updates child supplier framework lots when status change to Expired
        Parameters: Map of master framework lots to update
        Returns: - 
        Throws: -
    *************************************************************/   
	public static void checkAndUpdateSupplierFrameworkLotWhenExpired (Map<Id, Master_Framework_Lot__c> mapOldMFL, 
			Map<Id, Master_Framework_Lot__c> mapNewMFL){
		
		List<Master_Framework_Lot__c> liMFL = new List<Master_Framework_Lot__c> ();

		for (Master_Framework_Lot__c mflNew : mapNewMFL.values()){
			Master_Framework_Lot__c mflOld = mapOldMFL.get(mflNew.id);
			if (mflOld.Status__c != mflNew.Status__c && mflNew.Status__c == MFL_STATUS_EXPIRED){
				liMFL.add(mflNew);
			}
		}

		if (liMFL.size() > 0){
			updateSupplierFrameworkLotWhenExpired(liMFL);
		}
	}
	
    /************************************************************
        Purpose: Method  updates child supplier framework lots when status change to Expired
        Parameters: List of master framework lots to update
        Returns: - 
        Throws: -
    *************************************************************/   
	public static void updateSupplierFrameworkLotWhenExpired (List<Master_Framework_Lot__c> liMFL){
		List<Supplier_Framework_Lot__c> liSFL = [select id, Status__c from Supplier_Framework_Lot__c
			where Master_Framework_Lot__c in :liMFL and Status__c <> :SFL_STATUS_EXPIRED];

		for (Supplier_Framework_Lot__c sfl : liSFL){
			sfl.Status__c = SFL_STATUS_EXPIRED;
		}

		update liSFL;
	}
}