force-app/main/default/objects/Master_Framework__c/Master_Framework__c.object-meta.xml
<CustomObject>
    <description>This object represents Framework related to Opportunity, Enquiry, and Category.</description>
    <label>Framework</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Frameworks</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Framework__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>* Live : Open contracts
* Expired : Closed and no more data to be received
* Expired - Data Still Received : Closed to new contracts but still receiving data
* Non CCS Managed : Not managed by CCS
* Cancelled: Cancelled</description>
    <inlineHelpText>* Live : Open contracts
* Expired : Closed and no more data to be received
* Expired - Data Still Received : Closed to new contracts but still receiving data
* Non CCS Managed : Not managed by CCS
* Cancelled: Cancelled</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Future (Pipeline)</fullName>
            </value>
            <value>
                <fullName>Planned (Pipeline)</fullName>
            </value>
            <value>
                <fullName>Underway (Pipeline)</fullName>
            </value>
            <value>
                <fullName>Awarded (Pipeline)</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Expired - Data Still Received</fullName>
            </value>
            <value>
                <fullName>Non CCS Managed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Framework_Lot__c/Master_Framework_Lot__c.object-meta.xml
<CustomObject>
    <description>Object to hold information regarding Framework Lots</description>
    <label>Framework Lot</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Framework Lots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Framework_Lot__c/fields/Master_Framework__c.field-meta.xml
<CustomField>
    <fullName>Master_Framework__c</fullName>
    <description>Holds reference to Master Framework</description>
    <label>Framework</label>
    <referenceTo>Master_Framework__c</referenceTo>
    <relationshipLabel>Framework Lots</relationshipLabel>
    <relationshipName>Framework_Lots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Master_Framework_Lot__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>* Live : Open contracts
* Expired : Closed and no more data to be received
* Expired - Data Still Received : Closed to new contracts but still receiving data</description>
    <inlineHelpText>* Live : Open contracts
* Expired : Closed and no more data to be received
* Expired - Data Still Received : Closed to new contracts but still receiving data</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Expired - Data Still Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Supplier_Framework_Lot__c/Supplier_Framework_Lot__c.object-meta.xml
<CustomObject>
    <label>Framework Lot Supplier</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Framework Lot Suppliers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Framework_Lot__c/fields/Master_Framework_Lot__c.field-meta.xml
<CustomField>
    <fullName>Master_Framework_Lot__c</fullName>
    <label>Framework Lot</label>
    <referenceTo>Master_Framework_Lot__c</referenceTo>
    <relationshipLabel>Framework Lot Suppliers</relationshipLabel>
    <relationshipName>Supplier_Framework_Lots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Supplier_Framework_Lot__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>* Live : Open contracts
* Expired : Closed and no more data to be received
* Suspended : legally suspended due to a breach of contract</description>
    <inlineHelpText>* Live : Open contracts
* Expired : Closed and no more data to be received
* Suspended : legally suspended due to a breach of contract

Only suppliers with status of &apos;Live&apos; will be shown on the website.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FrameworkLotSupplierRelatedList_CX_Test.cls
/*********************************************************************
 Name:  FrameworkLotSupplierRelatedList_CX_test
 Copyright © 2016  Salesforce
 ======================================================
 ======================================================
 Purpose: Controller extension for FrameworkLotSupplierRelatedList
 ======================================================
 ======================================================
 History                                                            
 -------                                                            
 VERSION  AUTHOR            DATE             DETAIL             Description
		1.0  Cezary Zeleznicki  2016-12-02     Initial version
 *********************************************************************/
@isTest
private class FrameworkLotSupplierRelatedList_CX_Test {
	@testSetup
	static void createData() {
		insert UnitTestDataFactory.createOpsWorkflowStages();
		insert UnitTestDataFactory.createOpsWorkflowTemplates();
		
		List<Account> supplierAccounts = new List<Account>();
		for(Integer i = 0; i <100; i++) {
			supplierAccounts.add(
				UnitTestDataFactory.createSupplierAccount('Test supplier account - FrameworkLotSupplierRelatedList ' + i));
		}
		insert supplierAccounts;

		Master_Framework__c mf = UnitTestDataFactory.createMasterFramework();
		insert mf;
		Master_Framework_Lot__c mfl = UnitTestDataFactory.createMasterFrameworkLot(mf.Id);
		insert mfl;

		List<Supplier_Framework_Lot__c> suppFrameworkLots = new List<Supplier_Framework_Lot__c>();
		for(Integer i = 0; i < 100; i++) {
			Supplier_Framework_Lot__c sfl = UnitTestDataFactory.createSupplierFrameworkLot(mfl.Id, supplierAccounts[i].Id);
			sfl.Status__c = 'Live';
			suppFrameworkLots.add(sfl);
		}
		insert suppFrameworkLots;
	}

	static testMethod void test_getSuppliers() {
		Master_Framework__c mf = [SELECT Id FROM Master_Framework__c LIMIT 1];
		ApexPages.StandardController sc = new ApexPages.StandardController(mf);
		
		PageReference pageRef = Page.FrameworkLotSupplierRelatedList;
		pageRef.getParameters().put('id', String.valueOf(mf.Id));
		Test.setCurrentPage(pageRef);
		Test.startTest();
		FrameworkLotSupplierRelatedList_CX flsrl = new FrameworkLotSupplierRelatedList_CX(sc);
		List<FrameworkLotSupplierRelatedList_CX.SupplierWrapper> suppliers = flsrl.getSuppliers();
		Test.stopTest();

		System.assert(!suppliers.isEmpty(), 'Suppliers shouldn\'t be empty');
	}

	static testMethod void test_goBackToFramework() {
		Master_Framework__c mf = [SELECT Id FROM Master_Framework__c LIMIT 1];
		ApexPages.StandardController sc = new ApexPages.StandardController(mf);
		
		PageReference pageRef = Page.FrameworkLotSupplierRelatedList;
		pageRef.getParameters().put('id', String.valueOf(mf.Id));
		Test.setCurrentPage(pageRef);
		Test.startTest();
		FrameworkLotSupplierRelatedList_CX flsrl = new FrameworkLotSupplierRelatedList_CX(sc);
		PageReference pr = flsrl.goBackToFramework();
		Test.stopTest();

		System.assertEquals(sc.view().getUrl() + '?inline=0', pr.getUrl(),
			'Framework view should be returned');
	}

	static testMethod void test_goToList() {
		Master_Framework__c mf = [SELECT Id FROM Master_Framework__c LIMIT 1];
		ApexPages.StandardController sc = new ApexPages.StandardController(mf);
		
		PageReference pageRef = Page.FrameworkLotSupplierRelatedList;
		pageRef.getParameters().put('id', String.valueOf(mf.Id));
		Test.setCurrentPage(pageRef);
		Test.startTest();
		FrameworkLotSupplierRelatedList_CX flsrl = new FrameworkLotSupplierRelatedList_CX(sc);
		flsrl.getSuppliers();
		flsrl.goToList();
		Test.stopTest();

		System.assertEquals(50, flsrl.pageSize, 'Page size should be equal 50');
		System.assert(flsrl.showFullPage, 'Show full page param should be set');
	}

	static testMethod void test_SetControllerMethods() {
		Master_Framework__c mf = [SELECT Id FROM Master_Framework__c LIMIT 1];
		ApexPages.StandardController sc = new ApexPages.StandardController(mf);
		
		PageReference pageRef = Page.FrameworkLotSupplierRelatedList;
		pageRef.getParameters().put('id', String.valueOf(mf.Id));
		Test.setCurrentPage(pageRef);
		Test.startTest();
		FrameworkLotSupplierRelatedList_CX flsrl = new FrameworkLotSupplierRelatedList_CX(sc);
		flsrl.getSuppliers();
		Boolean hasNext = flsrl.getHasNext();
		Boolean hasPrevious = flsrl.getHasPrevious();
		Boolean isFirst = flsrl.getIsFirst();
		Integer recSize = flsrl.getRecordsSize();
		flsrl.first();
		flsrl.last();
		flsrl.previous();
		flsrl.next();
		Test.stopTest();

		System.assert(hasNext, 'Next page should be available');
		System.assert(!hasPrevious, 'Previous page should\'t be available');
		System.assert(isFirst, 'First page should be displayed');
		System.assertEquals(100, recSize, 'Record size in set controller should be 100');
		System.assertEquals(5, flsrl.pageSize, 'Page size should be equal 5');
	}

	static testMethod void test_failPath() {
		ApexPages.StandardController sc = new ApexPages.StandardController(new Master_Framework__c());
		
		PageReference pageRef = Page.FrameworkLotSupplierRelatedList;
		Test.setCurrentPage(pageRef);
		Test.startTest();
		FrameworkLotSupplierRelatedList_CX flsrl = new FrameworkLotSupplierRelatedList_CX(sc);
		List<FrameworkLotSupplierRelatedList_CX.SupplierWrapper> suppliers = flsrl.getSuppliers();
		Test.stopTest();

		System.assertEquals(null, suppliers, 'List of suppliers should be null');
	}
}