force-app/main/default/objects/Master_Framework__c/Master_Framework__c.object-meta.xml
<CustomObject>
    <description>This object represents Framework related to Opportunity, Enquiry, and Category.</description>
    <label>Framework</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Frameworks</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Framework__c/fields/CB_vs_current_comparator__c.field-meta.xml
<CustomField>
    <fullName>CB_vs_current_comparator__c</fullName>
    <inlineHelpText>If a value is also entered for a specific Lot on this framework, the Lot-level value will take precedence over the value at the framework level.</inlineHelpText>
    <label>Fw. CB vs. current comparator</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Master_Framework__c/fields/CB_vs_pre_defined_period__c.field-meta.xml
<CustomField>
    <fullName>CB_vs_pre_defined_period__c</fullName>
    <inlineHelpText>If a value is also entered for a specific Lot on this framework, the Lot-level value will take precedence over the value at the framework level.</inlineHelpText>
    <label>Fw. CB vs. pre-defined period</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Master_Framework__c/fields/CB_vs_previous_year__c.field-meta.xml
<CustomField>
    <fullName>CB_vs_previous_year__c</fullName>
    <inlineHelpText>If a value is also entered for a specific Lot on this framework, the Lot-level value will take precedence over the value at the framework level.</inlineHelpText>
    <label>Fw. CB vs. previous year</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Master_Framework__c/fields/Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Date__c</fullName>
    <description>This is the date this Framework expires</description>
    <inlineHelpText>Date when agreement was originally going to end</inlineHelpText>
    <label>Original End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Master_Framework_Lot__c/Master_Framework_Lot__c.object-meta.xml
<CustomObject>
    <description>Object to hold information regarding Framework Lots</description>
    <label>Framework Lot</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Framework Lots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Framework_Lot__c/fields/Award_Date__c.field-meta.xml
<CustomField>
    <fullName>Award_Date__c</fullName>
    <label>Award Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Master_Framework_Lot__c/fields/CB_vs_current_comparator__c.field-meta.xml
<CustomField>
    <fullName>CB_vs_current_comparator__c</fullName>
    <label>Lot CB vs. current comparator</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Master_Framework_Lot__c/fields/CB_vs_pre_defined_period__c.field-meta.xml
<CustomField>
    <fullName>CB_vs_pre_defined_period__c</fullName>
    <label>Lot CB vs. pre-defined period</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Master_Framework_Lot__c/fields/CB_vs_previous_year__c.field-meta.xml
<CustomField>
    <fullName>CB_vs_previous_year__c</fullName>
    <label>Lot CB vs. previous year</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Master_Framework_Lot__c/fields/Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Date__c</fullName>
    <description>each lot on a framework may have a different date</description>
    <inlineHelpText>Lot end date. Shown on website</inlineHelpText>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Master_Framework_Lot__c/fields/Final_Call_off_Date__c.field-meta.xml
<CustomField>
    <fullName>Final_Call_off_Date__c</fullName>
    <description>additional field to collect useful data</description>
    <label>Final Call-off Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Master_Framework_Lot__c/fields/Include_in_Related_List__c.field-meta.xml
<CustomField>
    <fullName>Include_in_Related_List__c</fullName>
    <formula>OR (
              
                  AND (Master_Framework_Lot_Number__c != &apos;0&apos;,
                  Name != &apos;Nil Return&apos;) ,
                  AND(
                 OR(
                  $Profile.Id = &apos;00eb0000000IfPP&apos;,
                  $Profile.Id = &apos;00eb0000000EgD5&apos;
                  ),
                  AND (Master_Framework_Lot_Number__c = &apos;0&apos;,
                  Name = &apos;Nil Return&apos;) 
                  
                  )
 )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Include in Related List</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Master_Framework_Lot__c/fields/Master_Framework__c.field-meta.xml
<CustomField>
    <fullName>Master_Framework__c</fullName>
    <description>Holds reference to Master Framework</description>
    <label>Framework</label>
    <referenceTo>Master_Framework__c</referenceTo>
    <relationshipLabel>Framework Lots</relationshipLabel>
    <relationshipName>Framework_Lots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Master_Framework_Lot__c/fields/Master_Framework_Lot_Number__c.field-meta.xml
<CustomField>
    <fullName>Master_Framework_Lot_Number__c</fullName>
    <description>Lot number field in SAFIRE</description>
    <inlineHelpText>Official number of the FW Lot.  Appears on the website</inlineHelpText>
    <label>Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Framework_Lot__c/fields/Nominal_Code__c.field-meta.xml
<CustomField>
    <fullName>Nominal_Code__c</fullName>
    <description>Code to show where the Framework sits in the Finance system (CODA)</description>
    <label>Nominal Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/bg_Framework_Lot_Related_List_Controller.cls
/*********************************************************************
 Name:  bg_Framework_Lot_Related_List_Controller
 History                                                            
 -------                                                            
 VERSION  AUTHOR            DATE             DETAIL             Description
   1.0   Conor Spark      September 2017                        Initial version
   1.1   Conor Spark      October   2017                        Update to include fullscreen
 *********************************************************************/
public class bg_Framework_Lot_Related_List_Controller 
{
    private List<Master_Framework_Lot__c> mfl;
    private Master_Framework__c mf;
    public Boolean canDelete{get; set;}
    public Boolean fullscreen{get; set;}
    public String redirectURL{get; set;}
    public Boolean shouldRedirect {public get; private set;}

    public bg_Framework_Lot_Related_List_Controller(ApexPages.StandardController controller) 
    {
     this.mf=(Master_Framework__c)controller.getRecord();
     shouldRedirect = false;

      if (Master_Framework_Lot__c.sObjectType.getDescribe().isDeletable()) 
        {
            canDelete = true;
        }else
        {
            canDelete = false;
        }
        String fscreen= ApexPages.currentPage().getParameters().get('fullscreen');
        if (fscreen == 'true')  
        {
            fullscreen = true;
        }else
        {
            fullscreen = false;
        }
        
     }
     
     //Retrieves the Framework Lots for the current Framework
     public List<Master_Framework_Lot__c> getFrameworkLots()
     {
         mf = [Select id, Name FROM Master_Framework__c where id =:mf.id];
         if (fullscreen){
             mfl = [Select id, Name, Master_Framework_Lot_Number__c, Nominal_Code__c, Award_Date__c, Final_Call_Off_Date__c, Expiry_Date__c,
             CB_vs_pre_defined_period__c,   CB_vs_previous_year__c, CB_vs_current_comparator__c
              from Master_Framework_Lot__c where Master_Framework__c =:mf.Id and Include_in_Related_List__c = true
              order by Master_Framework_Lot_Number__c];
              return mfl;
         }else{
         
             mfl = [Select id, Name, Master_Framework_Lot_Number__c, Nominal_Code__c, Award_Date__c, Final_Call_Off_Date__c, Expiry_Date__c,
             CB_vs_pre_defined_period__c,   CB_vs_previous_year__c, CB_vs_current_comparator__c
              from Master_Framework_Lot__c where Master_Framework__c =:mf.Id and Include_in_Related_List__c = true
              order by Master_Framework_Lot_Number__c LIMIT 5];
             return mfl;
         }
     }

     //redirects the page to the fullscreen version of the related list
     public PageReference redirectFullscreen()
     {
        shouldRedirect = true;
        redirectURL = '/apex/bg_Framework_Lot_Related_List?id='+mf.id + '&fullscreen=true';
        return null;
         

     }
     
     //redirects to a create new framework lot
     public Pagereference newFrameworkLot()
     {
         
        return new PageReference('/a0b/e?' + System.Label.Master_Framework_ID + '_lkid=' + mf.id + 
            '&' + System.Label.Master_Framework_ID + '='+ mf.Name + ' &retURL=%2F' + mf.id);

     }
        
     //redirects to the edit of the current framework lot
     public Pagereference editFrameworkLot()
     {
         String flid= ApexPages.currentPage().getParameters().get('flid'); 
         
        return new PageReference('/'+flid+'/e?retURL=%2F' + mf.Id );

     }
     
     //deletes current framework lot
      public Pagereference deleteFrameworkLot()
     {
         String flid= ApexPages.currentPage().getParameters().get('flid'); 
         
         Master_Framework_Lot__c mfToDelete = [Select id from Master_Framework_Lot__c where id =:flid limit 1];
         if(mfToDelete !=null && mfToDelete.id !=null){
          delete mfToDelete;
         }
        return null;

     }

     //returns value of current user's ability to delete framework lots
     public Boolean getCanDelete()
     {
       

        return canDelete;
        
     }
}