force-app/main/default/objects/Master_Framework__c/Master_Framework__c.object-meta.xml
<CustomObject>
    <description>This object represents Framework related to Opportunity, Enquiry, and Category.</description>
    <label>Framework</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Frameworks</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Framework_Lot__c/Master_Framework_Lot__c.object-meta.xml
<CustomObject>
    <description>Object to hold information regarding Framework Lots</description>
    <label>Framework Lot</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Framework Lots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Framework_Lot__c/fields/Master_Framework__c.field-meta.xml
<CustomField>
    <fullName>Master_Framework__c</fullName>
    <description>Holds reference to Master Framework</description>
    <label>Framework</label>
    <referenceTo>Master_Framework__c</referenceTo>
    <relationshipLabel>Framework Lots</relationshipLabel>
    <relationshipName>Framework_Lots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Supplier_Framework_Lot__c/Supplier_Framework_Lot__c.object-meta.xml
<CustomObject>
    <label>Framework Lot Supplier</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Framework Lot Suppliers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Framework_Lot__c/fields/Master_Framework_Lot__c.field-meta.xml
<CustomField>
    <fullName>Master_Framework_Lot__c</fullName>
    <label>Framework Lot</label>
    <referenceTo>Master_Framework_Lot__c</referenceTo>
    <relationshipLabel>Framework Lot Suppliers</relationshipLabel>
    <relationshipName>Supplier_Framework_Lots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Supplier_Framework_Lot__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Framework Lot Suppliers</relationshipLabel>
    <relationshipName>Supplier_Framework_Lots</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/bg_FrameworkLotSupplierContactSearchCtrl.cls
/*
 * bg_FrameworkLotSupplierContactSearchCtrl
 * Author: Conor Spark - Feb 2019
 * 
 * This is the controller for the bg_FrameworkLotSupplierContactSearch VF Component
 * 
 * */
public class bg_FrameworkLotSupplierContactSearchCtrl 
{
   
    
    public bg_ContactSearchResultCarrier searchResult {get; set;}
    
    public Contact con{get;set;}
    public String searchName {get;set;}
    public String frameworkId{get;set;}
    public List<Contact> contactList {get;set;}
    public List<ContactWrapper> contactWrapperList {get;set;}
    public List<String> validAccountIDs{get;set;}
    public integer totalRecs = 0;
    public integer OffsetSize = 0;
    public integer LimitSize= 10;
    
    public bg_FrameworkLotSupplierContactSearchCtrl()
    {        
        con = new Contact();
        contactList  = new List<Contact>();
        contactWrapperList = new List<ContactWrapper>();
        validAccountIDs = new List<String>();
        searchResult = new bg_ContactSearchResultCarrier();
        
    }
    
    // Get the Account ID filter that will be used for the search
    public void getValidAccountIDs()
    {
        
        List<Account> validAccounts = [SELECT ID from Account WHERE ID IN (SELECT Supplier__c  FROM Supplier_Framework_Lot__c WHERE Master_Framework_Lot__r.Master_Framework__r.Id =: frameworkId  )];
    	for (Account acc : validAccounts)
        {
            validAccountIDs.add(acc.Id);
        }
    }
    
    public void searchCon()
    {
        totalRecs = 0;
        OffsetSize = 0;
        searchContacts ();
    }
    
    // Query the database for the contacts that meet the requirements
    public void searchContacts()
    {        
		getValidAccountIDs();
        if(contactList != null && !contactList.isEmpty())
        {
            contactList.clear();
            contactWrapperList.clear();
        }
        
        
        if(searchName !=null && searchName !='')
        {
            String strQuery ='SELECT Name,Account.Name, AccountId ,Phone,Email From Contact';
            strQuery += ' WHERE (Name Like \'%' +searchName +'%\' ' + ' OR Account.Name Like \'%' +searchName +'%\') AND Account.Id IN :validAccountIDs ';
            strQuery += ' ORDER BY Name  ASC, CreatedDate DESC LIMIT :LimitSize OFFSET :OffsetSize';
            
            contactList  =Database.query(strQuery);
            totalRecs = contactList.size();
            
            if(contactList.size()> 0)
            {
                for (Contact c : contactList)
                {
					contactWrapperList.add(new ContactWrapper(c));
                }
            }
        }
        else
        {
            
		}
        
    }
    
    // Navigation section
    public void FirstPage()
    {
        OffsetSize = 0;
        searchContacts();
    }
    public void previous()
    {
        OffsetSize = (OffsetSize-LimitSize);
        searchContacts();
    }
    public void next()
    {
        OffsetSize = OffsetSize + LimitSize;
        searchContacts();
    }
    public void LastPage()
    {
        OffsetSize = totalrecs - math.mod(totalRecs,LimitSize);
        searchContacts();
    }
    public boolean getprev()
    {
        
        if(OffsetSize == 0)
        {
            
            return true;
        }
        else 
        {
            
            return false;
        }
    }
    public boolean getnxt()
    {
        if((OffsetSize + LimitSize) > totalRecs)
        {
            
            return true;
        }
        else 
        {
            
            return false;
        } 
    }
    
    // When a search result is clicked on the page, highlight it
    public void chooseContact()
    {
        searchResult.contactRecord = con;
        for (ContactWrapper cw : contactWrapperList)
        {
            if (cw.contactRecord.Id == con.Id)
            {
            	cw.checked = true; 
			}
            else
            {
				cw.checked = false;
            }
        }
    
        
    }
    
    public List<ContactWrapper> getContactWrapperList()
    {
        return contactWrapperList;
    }
    
    // Inner class to hold the contact record and its checked state
    public class ContactWrapper
    {
        public Contact contactRecord{get; set;}
        public Boolean checked{get; set;}
        
        public ContactWrapper(Contact contactRecord)
        {
			this.contactRecord = contactRecord;
            checked = false;
        }
    }
    
 
    

}