force-app/main/default/objects/Master_Framework__c/Master_Framework__c.object-meta.xml
<CustomObject>
    <description>This object represents Framework related to Opportunity, Enquiry, and Category.</description>
    <label>Framework</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Frameworks</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Framework__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>* Live : Open contracts
* Expired : Closed and no more data to be received
* Expired - Data Still Received : Closed to new contracts but still receiving data
* Non CCS Managed : Not managed by CCS
* Cancelled: Cancelled</description>
    <inlineHelpText>* Live : Open contracts
* Expired : Closed and no more data to be received
* Expired - Data Still Received : Closed to new contracts but still receiving data
* Non CCS Managed : Not managed by CCS
* Cancelled: Cancelled</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Future (Pipeline)</fullName>
            </value>
            <value>
                <fullName>Planned (Pipeline)</fullName>
            </value>
            <value>
                <fullName>Underway (Pipeline)</fullName>
            </value>
            <value>
                <fullName>Awarded (Pipeline)</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Expired - Data Still Received</fullName>
            </value>
            <value>
                <fullName>Non CCS Managed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Framework_Lot__c/Master_Framework_Lot__c.object-meta.xml
<CustomObject>
    <description>Object to hold information regarding Framework Lots</description>
    <label>Framework Lot</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Framework Lots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Framework_Lot__c/fields/Master_Framework__c.field-meta.xml
<CustomField>
    <fullName>Master_Framework__c</fullName>
    <description>Holds reference to Master Framework</description>
    <label>Framework</label>
    <referenceTo>Master_Framework__c</referenceTo>
    <relationshipLabel>Framework Lots</relationshipLabel>
    <relationshipName>Framework_Lots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Master_Framework_Lot__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>* Live : Open contracts
* Expired : Closed and no more data to be received
* Expired - Data Still Received : Closed to new contracts but still receiving data</description>
    <inlineHelpText>* Live : Open contracts
* Expired : Closed and no more data to be received
* Expired - Data Still Received : Closed to new contracts but still receiving data</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Expired - Data Still Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Supplier_Framework_Lot__c/Supplier_Framework_Lot__c.object-meta.xml
<CustomObject>
    <label>Framework Lot Supplier</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Framework Lot Suppliers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Framework_Lot__c/fields/Master_Framework_Lot__c.field-meta.xml
<CustomField>
    <fullName>Master_Framework_Lot__c</fullName>
    <label>Framework Lot</label>
    <referenceTo>Master_Framework_Lot__c</referenceTo>
    <relationshipLabel>Framework Lot Suppliers</relationshipLabel>
    <relationshipName>Supplier_Framework_Lots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Supplier_Framework_Lot__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>* Live : Open contracts
* Expired : Closed and no more data to be received
* Suspended : legally suspended due to a breach of contract</description>
    <inlineHelpText>* Live : Open contracts
* Expired : Closed and no more data to be received
* Suspended : legally suspended due to a breach of contract

Only suppliers with status of &apos;Live&apos; will be shown on the website.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Supplier_Framework_Lot__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <label>Supplier</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Framework Lot Suppliers</relationshipLabel>
    <relationshipName>Supplier_Framework_Lots</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Supplier_Framework_Lot__c/fields/Supplier_Code__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Code__c</fullName>
    <description>code for Finance (CODA) system</description>
    <label>Supplier Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FrameworkLotSupplierRelatedList_CX.cls
/*********************************************************************
 Name:  FrameworkLotSupplierRelatedList_CX
 Copyright © 2016  Salesforce
 ======================================================
 ======================================================
 Purpose: Controller extension for FrameworkLotSupplierRelatedList
 ======================================================
 ======================================================
 History                                                            
 -------                                                            
 VERSION  AUTHOR            DATE             DETAIL             Description
		1.0  Cezary Zeleznicki  2016-12-01     Initial version
 *********************************************************************/
public with sharing class FrameworkLotSupplierRelatedList_CX {

	public final static String SHOW_FULL_PAGE_PARAM = 'showFullPage';
	private final Master_Framework__c framework;
	public Boolean showFullPage {get; private set;}
	private ApexPages.StandardSetController setCon;
	private List<SupplierWrapper> suppliers;
	@testVisible
	private Integer pageSize;

	public FrameworkLotSupplierRelatedList_CX(ApexPages.StandardController stdController) {
		this.framework = (Master_Framework__c)stdController.getRecord();
		this.showFullPage = ApexPages.currentPage().getParameters().get(SHOW_FULL_PAGE_PARAM) != null;
		this.pageSize = showFullPage ? 50 : 5;
		this.setCon = fetchStandardSetController();
	}

	private ApexPages.StandardSetController fetchStandardSetController() {
		ApexPages.StandardSetController standardSetController;
		if(framework.Id == null) {
			return null;
		}
		List<Master_Framework_Lot__c> frameworkLots = fetchFrameworkLots(framework.Id);

		List<Supplier_Framework_Lot__c> suppFrameworkLots = [
			SELECT Id, Name, Master_Framework_Lot__c, Master_Framework_Lot__r.Name, Supplier_Code__c,
				Status__c, Supplier__c, Supplier__r.Name
			FROM Supplier_Framework_Lot__c 
			WHERE Master_Framework_Lot__c IN :frameworkLots
				AND Status__c = 'Live'
			ORDER BY Supplier__r.Name ASC
		];
		Map<Id, Supplier_Framework_Lot__c> suppId2SupplierFrameworkLot = new Map<Id, Supplier_Framework_Lot__c>();
		List<Account> suppliers = new List<Account>();
		List<Supplier_Framework_Lot__c> sortedSupplierFrameworkLots = new List<Supplier_Framework_Lot__c>();
		for(Supplier_Framework_Lot__c sfl : suppFrameworkLots) {
			if(suppId2SupplierFrameworkLot.containsKey(sfl.Supplier__c)) {
				continue;
			}
			suppId2SupplierFrameworkLot.put(sfl.Supplier__c, sfl);
			suppliers.add(sfl.Supplier__r);
		}

		suppliers.sort();
		for(Account a : suppliers) {
			sortedSupplierFrameworkLots.add(suppId2SupplierFrameworkLot.get(a.Id));
		}

		standardSetController = new ApexPages.StandardSetController(sortedSupplierFrameworkLots);
		return standardSetController;
	}

	private List<Master_Framework_Lot__c> fetchFrameworkLots(Id frameworkId) {
		return [
			SELECT Id
			FROM Master_Framework_Lot__c
			WHERE Master_Framework__c = :frameworkId
		];
	}

	public List<SupplierWrapper> getSuppliers() {
		if(setCon == null) {
			return null;
		}
		suppliers = new List<SupplierWrapper>();

		setCon.setPageSize(pageSize);

		for(Supplier_Framework_Lot__c sfl : (List<Supplier_Framework_Lot__c>)setCon.getRecords()) {
			suppliers.add(new SupplierWrapper(sfl.Supplier__r.Name, sfl.Supplier__c, sfl));
		}
		
		return suppliers;
	}

	public PageReference goBackToFramework() {
		PageReference pr = new ApexPages.StandardController(framework).view();
		pr.getParameters().put('inline', '0');
		pr.setRedirect(true);
		return pr;
	}

	public PageReference goToList() {
		PageReference pr = Page.FrameworkLotSupplierRelatedList;
		pr.getParameters().put(SHOW_FULL_PAGE_PARAM, '1');
		showFullPage = true;
		pageSize = 50;
		return pr;
	}

	public Integer getRecordsSize() {
		return setCon.getResultSize();
	}

	public Boolean getHasNext() {
		return setCon.getHasNext();
	}

	public Boolean getHasPrevious() {
		return setCon.getHasPrevious();
	}

	public Boolean getIsFirst() {
		return setCon.getPageNumber() == 1;
	}

	public void first() {
		setCon.first();
	}

	public void last() {
		setCon.last();
	}

	public void previous() {
		setCon.previous();
	}

	public void next() {
		setCon.next();
	}

	public class SupplierWrapper {
		public String name {get; private set;}
		public Id id {get; private set;}
		public Supplier_Framework_Lot__c suppFrameworkLot {get; private set;}

		public SupplierWrapper(String name, Id id, Supplier_Framework_Lot__c suppFrameworkLot) {
			this.name = name;
			this.id = id;
			this.suppFrameworkLot = suppFrameworkLot;
		}
	}
}