force-app/main/default/objects/Master_Framework__c/Master_Framework__c.object-meta.xml
<CustomObject>
    <description>This object represents Framework related to Opportunity, Enquiry, and Category.</description>
    <label>Framework</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Frameworks</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Framework__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>* Live : Open contracts
* Expired : Closed and no more data to be received
* Expired - Data Still Received : Closed to new contracts but still receiving data
* Non CCS Managed : Not managed by CCS
* Cancelled: Cancelled</description>
    <inlineHelpText>* Live : Open contracts
* Expired : Closed and no more data to be received
* Expired - Data Still Received : Closed to new contracts but still receiving data
* Non CCS Managed : Not managed by CCS
* Cancelled: Cancelled</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Future (Pipeline)</fullName>
            </value>
            <value>
                <fullName>Planned (Pipeline)</fullName>
            </value>
            <value>
                <fullName>Underway (Pipeline)</fullName>
            </value>
            <value>
                <fullName>Awarded (Pipeline)</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Expired - Data Still Received</fullName>
            </value>
            <value>
                <fullName>Non CCS Managed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Framework_Lot__c/Master_Framework_Lot__c.object-meta.xml
<CustomObject>
    <description>Object to hold information regarding Framework Lots</description>
    <label>Framework Lot</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Framework Lots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Framework_Lot__c/fields/Master_Framework__c.field-meta.xml
<CustomField>
    <fullName>Master_Framework__c</fullName>
    <description>Holds reference to Master Framework</description>
    <label>Framework</label>
    <referenceTo>Master_Framework__c</referenceTo>
    <relationshipLabel>Framework Lots</relationshipLabel>
    <relationshipName>Framework_Lots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Master_Framework_Lot__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>* Live : Open contracts
* Expired : Closed and no more data to be received
* Expired - Data Still Received : Closed to new contracts but still receiving data</description>
    <inlineHelpText>* Live : Open contracts
* Expired : Closed and no more data to be received
* Expired - Data Still Received : Closed to new contracts but still receiving data</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Expired - Data Still Received</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Supplier_Framework_Lot__c/Supplier_Framework_Lot__c.object-meta.xml
<CustomObject>
    <label>Framework Lot Supplier</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Framework Lot Suppliers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Framework_Lot__c/fields/Master_Framework_Lot__c.field-meta.xml
<CustomField>
    <fullName>Master_Framework_Lot__c</fullName>
    <label>Framework Lot</label>
    <referenceTo>Master_Framework_Lot__c</referenceTo>
    <relationshipLabel>Framework Lot Suppliers</relationshipLabel>
    <relationshipName>Supplier_Framework_Lots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Supplier_Framework_Lot__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>* Live : Open contracts
* Expired : Closed and no more data to be received
* Suspended : legally suspended due to a breach of contract</description>
    <inlineHelpText>* Live : Open contracts
* Expired : Closed and no more data to be received
* Suspended : legally suspended due to a breach of contract

Only suppliers with status of &apos;Live&apos; will be shown on the website.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MasterFrameworkLotTriggerHandlerTest.cls
@isTest (seeAllData=false)
private class MasterFrameworkLotTriggerHandlerTest
{
	private static final Integer NO_RECORDS = 303;
	private static final String MFL_Name = 'UnitTest MasterFrameworkLotTriggerHandler';
	
	@testSetup
	static void setupTest(){
		Account org = UnitTestDataFactory.createSupplierAccount('MasterFrameworkLotTriggerHandlerTest');
		insert org;

		Master_Framework__c mf = UnitTestDataFactory.createMasterFramework();
		insert mf;

		Master_Framework_Lot__c mfl = UnitTestDataFactory.createMasterFrameworkLot(mf.id);
		mfl.Name = MFL_Name;
		insert mfl;

		List<Supplier_Framework_Lot__c> liSFL = new List<Supplier_Framework_Lot__c> ();

		for (Integer i=0; i < NO_RECORDS; i++){
			liSFL.add(UnitTestDataFactory.createSupplierFrameworkLot(mfl.id, org.id));
		}

		insert liSFL;
		
	}

	@isTest
	static void itShouldUpdateStatusWhenChangedInMFL(){
		// Given
		Master_Framework_Lot__c mfl = [Select Id, Name, Status__c from Master_Framework_Lot__c 
			where Name = :MFL_Name limit 1];
		System.assertEquals(0, [Select id from Supplier_Framework_Lot__c 
				where Master_Framework_Lot__c = :mfl.id 
					and Status__C = :MasterFrameworkLotTriggerHandler.SFL_STATUS_EXPIRED].size(),
			'Initially no Suplier framework lots should have expire status'
		);

		// When
		Test.startTest();
			mfl.Status__c = MasterFrameworkLotTriggerHandler.MFL_STATUS_EXPIRED;
			update mfl;
		Test.stopTest();

		// Then
		System.assertEquals(NO_RECORDS, [Select id from Supplier_Framework_Lot__c 
				where Master_Framework_Lot__c = :mfl.id 
					and Status__C = :MasterFrameworkLotTriggerHandler.SFL_STATUS_EXPIRED].size(),
			'Initially no Suplier framework lots should have expire status'
		);
	}
}